# Ch. 1: Tasks & Quizzes {.unnumbered}

::: {.callout-tip collapse="false"}
#### Your turn! {.unnumbered}

This quiz encourages you to do some quick internet searches to find out more about open-source software.

[**Q1.1**]{style="color:green;"} Which of these is an open-source alternative to Microsoft Word?

```{r}
#| echo: false
#| label: "Q1.1"
library(checkdown)
check_question("LibreOffice Writer", 
               options = c("LibreOffice Writer", "Google Docs", "Pages"), 
               type = "radio",
random_answer_order = TRUE,
button_label = "Check answer", q_id = "Q1.1",
right = "Correct! And the good news is that, in Task 1 (see below), you will install LibreOffice Writer as part of the LibreOffice package.",
wrong = "No, this software is not open source. The source code is not available to all.")
```

[**Q1.2**]{style="color:green;"} Which of these is an open-source alternative to Microsoft Powerpoint?

```{r}
#| echo: false
#| label: "Q1.2"

check_question("LibreOffice Impress", 
               options = c("Keynote", "Google Slides", "LibreOffice Impress"), 
               type = "radio",
random_answer_order = TRUE,
button_label = "Check answer", q_id = "Q1.2",
right = "Correct! And the good news is that, in Task 1 (see below), you will install LibreOffice Impress as part of the LibreOffice package.",
wrong = "No, this software is proprietary.")
```

[**Q1.3**]{style="color:green;"} Not only can software be open source, programming languages can, too. In fact, most modern programming languages are open source. In this book, we will focus on the open-source programming language `R`. Which of these is *not* an open-source programming language?

```{r}
#| echo: false
#| label: "Q1.3"

check_question("MATLAB", 
               options = c("MATLAB", "JavaScript", "Python"), 
               type = "radio",
button_label = "Check answer", q_id = "Q1.3",
random_answer_order = TRUE,
right = "Correct. MATLAB is one of the few genuinely closed-source programming languages that continue to be used in research.",
wrong = "No, just like `R`, this programming language is also open source.")
```

[**Q1.4**]{style="color:green;"} There are also many open-source operating systems. Which of these is an open-source alternative to the operating system Windows?

```{r}
#| echo: false
#| label: "Q1.4"

check_question("Ubuntu", 
               options = c("MacOS", "Ubuntu", "iOS"), 
               type = "radio",
random_answer_order = TRUE,
button_label = "Check answer", q_id = "Q1.4",
right = "Correct! Ubuntu is one of many Linux distributions, a family of open source operating systems. You can find out more here: https://itsfoss.com/getting-started-with-ubuntu/.",
wrong = "No, this operating system is not open source. It is owned by Apple.")
```
:::
::: {.callout-tip collapse="false"}
#### Your turn! {.unnumbered}

[**Q1.5**]{style="color:green;"} Is it possible to reuse @fig-OER on a company website?

```{r}
#| echo: false
#| label: "Q1.5"

check_question("Yes, but you must mention the name of the artist.",
               options = c("Yes, but you must mention the name of the artist.", "Yes, but you must mention the image's sell-by date.", "Yes, but only if it is the website of a non-profit company.", "Yes, but only after having obtained written consent from the artist."), 
               type = "radio",
               q_id = "Q1.5", 
               random_answer_order = TRUE,
               button_label = "Check answer",
               right = "That's right!",
               wrong = "No, that's not what the CC-BY license means.")
```

[**Q1.6**]{style="color:green;"} Which of these resources can be published as OERs?

```{r}
#| echo: false
#| label: "Q1.6"

check_question(c("Serious games", "Textbooks", "Course assessments", "Homework tasks", "Lesson plans", "Course syllabi", "Lecture slides", "Massive Open Online Courses"), 
               options = c("Serious games", "Textbooks", "Course assessments", "Homework tasks", "Lesson plans", "Course syllabi", "Lecture slides", "Massive Open Online Courses"),
               type = "check",
               q_id = "Q1.6", 
               random_answer_order = TRUE,
               button_label = "Check answer",
               right = "Exactly, all of them! And many more, as you can see from this long list of material types: <https://oercommons.org/oer>",
               wrong = "That's a good start, but there are more. Check out the material types listed on the OER commons database: <https://oercommons.org/oer>")
```
:::
### Check your progress 🌟 {.unnumbered}

You have successfully completed [`r checkdown::insert_score()` out of 6 questions]{style="color:green;"} in this chapter.
