project:
  type: book
  output-dir: PDF
book:
  date: "25 March 2026"
  date-format: "D MMMM YYYY"
  chapters:
  - index.qmd
  - 1_OpenScholarship.qmd
  - 2_Data.qmd
  - 3_DataManagement.qmd
  - 4_InstallingR.qmd
  - 5_GettingStaRted.qmd 
  - 6_ImpoRtingData.qmd 
  - 7_VariablesFunctions.qmd 
  - 8_DescriptiveStats.qmd
  - 9_DataWrangling.qmd
  - 10_Dataviz.qmd 
  - 11_Inferential.qmd
  - 12_SimpleLinearRegression.qmd
  - 13_MultipleLinearRegression.qmd
  - 14_LiterateProgramming.qmd
  - 15_AI.qmd
  - References.qmd
  
execute:
  fig-asp: 0.618
  fig-width: 7

lightbox: false

format:
  pdf:
    toc: true
    #template: 
    #documentclass: scrreprt
    #word-count: "{{< words-sum body-note >}}"
    keep-tex: true
    colorlinks: true
    prefer-html: true
    include-in-header:
       text: |
         \usepackage{emoji}
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
include-before-body:
  text: |
    \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
      showspaces = false,
      showtabs = false,
      breaksymbolleft={},
      breaklines
      % Note: setting commandchars=\\\{\} here will cause an error 
    }
