---
#bibliography: references.bib
engine: knitr
---

```{css}
#| echo: false
p {
  text-align: justify
}
```

# Further resources

## Recommended resources specific to the language sciences

-   Brezina, Vaclav. 2018. Statistics in Corpus Linguistics: A Practical Guide. Cambridge: Cambridge University Press. https://doi.org/10.1017/9781316410899.

-   Desagulier, Guillaume. 2017. Corpus Linguistics and Statistics with R: Introduction to Quantitative Methods in Linguistics (Quantitative Methods in the Humanities and Social Sciences). Cham: Springer International Publishing.

-   Gries, Stefan Thomas. 2013. Statistics for linguistics with R: a practical introduction. 2nd revised edition. Berlin: De Gruyter Mouton.

-   LADAL contributors. Tutorials of the Language Technology and Data Analysis Laboratory. <https://ladal.edu.au/tutorials.html>  `Open Educational Resource`.

-   Levshina, Natalia. 2015. How to do linguistics with R: Data exploration and statistical analysis. Amsterdam: John Benjamins.

-   Schneider, Dr Gerold & Max Lauber. 2020. Statistics for Linguists. <https://dlf.uzh.ch/openbooks/statisticsforlinguists/>  `Open Educational Resource`.

-   Winter, Bodo. 2019. Statistics for Linguists: An Introduction Using R. New York: Routledge. [https://doi.org/10.4324/9781315165547](https://doi.org/10.1017/9781316410899).

## Further Open Educational Resources (in no particular order) 

-   Diez, David, Mine Cetinkaya-Rundel, Christopher Barr & OpenIntro. 2015. OpenIntro Statistics. Leanpub. <https://leanpub.next/os>.
-   Guide to Effect Sizes and Confidence Intervals: <https://matthewbjane.quarto.pub/guide-to-effect-sizes-and-confidence-intervals/>
-   Happy Git and GitHub for the useR: <https://happygitwithr.com/>
-   Quarto & reproducibility: <https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/index.html>
-   Modern Data Visualization with R: <https://rkabacoff.github.io/datavis>
-   Building reproducible analytical pipelines with R: <https://raps-with-r.dev/>
-   Modern Plain Text Computing: <https://mptc.io/content/01-content.html>
-   <https://www.data-to-viz.com/>
-   Interpreting data visualisation: <https://pressbooks.library.torontomu.ca/criticaldataliteracy/>
-   Improve your statistical inferences: <https://lakens.github.io/statistical_inferences/>
-   What they forgot to teach you about R: <https://rstats.wtf/>
-   Introduction to Data Science: <https://florian-huber.github.io/data_science_course/book/cover.html>
-   Data Science in Education Using R: <https://datascienceineducation.com/>
-   Models Demystified: A Practical Guide from t-tests to Deep Learning
<https://m-clark.github.io/book-of-models/>
-   Data Visualization in R <https://datavizf23.classes.andrewheiss.com/>
