{
  "hash": "20ce745c60e911d903a73bdc01e890eb",
  "result": {
    "engine": "knitr",
    "markdown": "# Ch. 15: Tasks & Quizzes {.unnumbered}\n---\n\n::: {.callout-tip collapse=\"false\"}\n#### Your turn! {.unnumbered}\n\n[**Q15.1**]{style=\"color:green;\"} Which of the following analogies have (rightly or wrongly) been used by different scholars to refer to Large Language Models (LLMs)? You may have heard of one or a few of these, but you can guess them all?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_1\" onsubmit=\"return validate_form_Q15_1()\" method=\"post\">\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_1_1\" value=\"Stochastic parrots\"/>\nStochastic parrots\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_1_2\" value=\"Automated plagiarism\"/>\nAutomated plagiarism\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_1_3\" value=\"Spicy autocomplete\"/>\nSpicy autocomplete\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_1_4\" value=\"Ask-Einstein-anything engine\"/>\nAsk-Einstein-anything engine\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_1_5\" value=\"Bullshit\"/>\nBullshit\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_1_6\" value=\"Magic research wand\"/>\nMagic research wand\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_1_7\" value=\"Synthetic text extruding machines\"/>\nSynthetic text extruding machines\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_1_8\" value=\"Kitsch\"/>\nKitsch\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_1\"></div>\n</form>\n<script>function validate_form_Q15_1() {var text; var x1 = document.getElementById('answer_Q15_1_1'); var x2 = document.getElementById('answer_Q15_1_2'); var x3 = document.getElementById('answer_Q15_1_3'); var x4 = document.getElementById('answer_Q15_1_4'); var x5 = document.getElementById('answer_Q15_1_5'); var x6 = document.getElementById('answer_Q15_1_6'); var x7 = document.getElementById('answer_Q15_1_7'); var x8 = document.getElementById('answer_Q15_1_8'); if (x1.checked == true&x2.checked == true&x3.checked == true&x4.checked == false&x5.checked == true&x6.checked == false&x7.checked == true&x8.checked == true){text = 'That’s right, well done! Click on the tab below to find out a little more about each metaphor.';} else {text = 'Not quite. You will need to select all the analogies that have (rightly or wrongly) been used to described LLMs/AI to get this question right. For a tip, check the hint below.';} document.getElementById('result_Q15_1').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1;res1 = document.getElementById('result_Q15_1').innerText == 'That’s right, well done! Click on the tab below to find out a little more about each metaphor.';text = res1;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hint_24071\" onclick=\"return show_hint_24071()\">🦜 Click on the parrot for a hint.</div>\n<div id=\"result_24071\" onclick=\"return show_hint_24071()\"></div>\n<script>function show_hint_24071(){var x = document.getElementById('result_24071').innerHTML; if(!x){document.getElementById('result_24071').innerHTML = 'Six of the above analogies have been used to describe LLMs by academics and scholars. Click on the tab below to find out more about these metaphors.';} else {document.getElementById('result_24071').innerHTML = '';}}</script>\n```\n\n:::\n:::\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n#### The power of language: Metaphors of AI and LLMs ✨ {.unnumbered}\n\nThe term 'stochastic parrot' 🦜 is probably the best known LLM metaphor. It was introduced by computational linguist [Emily M. Bender and colleagues in 2021](https://doi.org/10.1145/3442188.3445922) to characterise LLMs as systems that mimic text without true understanding, highlighting their limitations in processing meaning. This metaphor emphasises that LLMs generate outputs based on statistical patterns in their training data, similar to how parrots mimic sounds without comprehension.\n\nIn 2022, the cognitive scientist Iris Van Rooij published a [blog post](https://irisvanrooijcogsci.com/2022/12/29/against-automated-plagiarism/) in which she succinctly explains why she believes that LLMs cannot legitimately be used for academic writing because they essentially \"automate plagiarism\".\n\nThe 'spicy autocomplete' metaphor 🌶️ is difficult to trace back to one or more specific author(s). It suggests that LLMs are just fancy versions of a smart phone’s predictive text, which predict the next word based on what came before, except that LLMs add some randomness, i.e. spice, to the output. This framing also implies that LLMs are pattern-matching algorithms without real understanding or problem-solving ability (see [Groß 2024](https://publikationen.soziologie.de/index.php/soziologie/en/article/view/1798)).\n\nIn 2024, Hicks, Humphries & Slater published a paper in the journal 'Ethics and Information Technology' entitled '[ChatGPT is bullshit](https://doi.org/10.1007/s10676-024-09775-5)', in which they argue that the output of LLMs is best understood as 'bullshit' in the philosophical sense described by [Frankfurt (2005)](https://en.wikipedia.org/wiki/On_Bullshit) because LLMs are indifferent to the truth of their outputs.\n\n'Synthetic text extruding machines' is a term that Emily M. Bender and Alex Hanna like to use, e.g. in their 2025 book entitled '[The AI Con: How to Fight Big Tech's Hype and Create the Future We Want](https://thecon.ai/)'. They describe the process of LLM-generated texts by explaining that, \"\\[l\\]ike an industrial plastic process, language corpora are forced through complicated machinery to produce a product that looks like communicative language, but without any intent or thinking mind behind it.\"\n\nAs an alternative to well-established metaphors such as the ones listed above, classical philologist Gyburg Uhlmann proposed 'kitsch' as a new metaphor to describe the output of LLMs. She argues that 'kitsch' \"is particularly suitable for analytically illuminating a previously neglected feature of LLM-based images and texts: their tendency to produce homogeneous and average content, which is \\[...\\] leading to the equalisation of language, style and argument\" ([Uhlmann 2025](https://arxiv.org/pdf/2509.16794)).\n:::\n::: {.callout-tip collapse=\"false\"}\n#### Your turn! {.unnumbered}\n\n[**Q15.2**]{style=\"color:green;\"} Read Jeff Pooley's short commentary '[The Matthew Effect in AI Summary](https://www.jeffpooley.com/2025/11/the-matthew-effect-in-ai-summary/)' ([archived version](https://web.archive.org/web/20251225173407/https://www.jeffpooley.com/2025/11/the-matthew-effect-in-ai-summary/)). What does the Matthew Effect refer to?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_2\" onsubmit=\"return validate_form_Q15_2()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_Q15_2\" id=\"answer_Q15_2_1\" value=\"It refers to the practice of LLM-assisted plagiarism in academic writing.\"/>\nIt refers to the practice of LLM-assisted plagiarism in academic writing.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_2\" id=\"answer_Q15_2_2\" value=\"It refers to the positive impact of open-access publishing on research dissemination.\"/>\nIt refers to the positive impact of open-access publishing on research dissemination.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_2\" id=\"answer_Q15_2_3\" value=\"It describes how successful researchers receive more recognition and opportunities, leading to more success.\"/>\nIt describes how successful researchers receive more recognition and opportunities, leading to more success.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_2\" id=\"answer_Q15_2_4\" value=\"It describes how successful researchers tend to be harsher in peer reviewing processes in order to remain successful themselves.\"/>\nIt describes how successful researchers tend to be harsher in peer reviewing processes in order to remain successful themselves.\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_2\"></div>\n</form>\n<script>function validate_form_Q15_2() {var x, text; var x = document.forms['form_Q15_2']['answer_Q15_2'].value;if (x == 'It describes how successful researchers receive more recognition and opportunities, leading to more success.'){text = 'That’s right! ✅';} else {text = 'No, that’s not it. Re-read the article linked in the question and/or check the hint.';} document.getElementById('result_Q15_2').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2;res1 = document.getElementById('result_Q15_1').innerText == 'That’s right, well done! Click on the tab below to find out a little more about each metaphor.'; res2 = document.getElementById('result_Q15_2').innerText == 'That’s right! ✅';text = res1 + res2;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hint_11798\" onclick=\"return show_hint_11798()\">🦜 Click on the parrot for a hint.</div>\n<div id=\"result_11798\" onclick=\"return show_hint_11798()\"></div>\n<script>function show_hint_11798(){var x = document.getElementById('result_11798').innerHTML; if(!x){document.getElementById('result_11798').innerHTML = 'The Matthew effect is named after the following passage from the Bible: “For to every one who has will more be given, and he will have abundance; but from him who has not, even what he has will be taken away” (Matthew 25:29)”.';} else {document.getElementById('result_11798').innerHTML = '';}}</script>\n```\n\n:::\n:::\n\n\n[**Q15.3**]{style=\"color:green;\"} Which term describes the phenomenon whereby the contributions of marginalised female scientists are overlooked or attributed to their male colleagues?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_3\" onsubmit=\"return validate_form_Q15_3()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_Q15_3\" id=\"answer_Q15_3_1\" value=\"The Dunning-Kruger effect\"/>\nThe Dunning-Kruger effect\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_3\" id=\"answer_Q15_3_2\" value=\"The Matilda effect\"/>\nThe Matilda effect\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_3\" id=\"answer_Q15_3_3\" value=\"The Harriet effect\"/>\nThe Harriet effect\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_3\" id=\"answer_Q15_3_4\" value=\"The Margaret Rossiter effect\"/>\nThe Margaret Rossiter effect\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_3\"></div>\n</form>\n<script>function validate_form_Q15_3() {var x, text; var x = document.forms['form_Q15_3']['answer_Q15_3'].value;if (x == 'The Matilda effect'){text = 'Correct!';} else {text = 'Incorrect.';} document.getElementById('result_Q15_3').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3;res1 = document.getElementById('result_Q15_1').innerText == 'That’s right, well done! Click on the tab below to find out a little more about each metaphor.'; res2 = document.getElementById('result_Q15_2').innerText == 'That’s right! ✅'; res3 = document.getElementById('result_Q15_3').innerText == 'Correct!';text = res1 + res2 + res3;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hint_84721\" onclick=\"return show_hint_84721()\">🦜 Click on the parrot for a hint.</div>\n<div id=\"result_84721\" onclick=\"return show_hint_84721()\"></div>\n<script>function show_hint_84721(){var x = document.getElementById('result_84721').innerHTML; if(!x){document.getElementById('result_84721').innerHTML = 'This effect is named after Matilda Joslyn Gage, a 19<sup>th</sup>-century women’s rights activist.';} else {document.getElementById('result_84721').innerHTML = '';}}</script>\n```\n\n:::\n:::\n\n\n[**Q15.4**]{style=\"color:green;\"} According to @pooleyMatthewEffectAI2025, which of the following biases in academia are likely to be aggravated by the use of Large Language Models (LLMs) to summarise academic literature and write research articles?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_4\" onsubmit=\"return validate_form_Q15_4()\" method=\"post\">\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_4_1\" value=\"Inequalities favouring central, influential regions over less influential, so-called &quot;peripheral&quot; regions\"/>\nInequalities favouring central, influential regions over less influential, so-called \"peripheral\" regions\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_4_2\" value=\"Racial biases\"/>\nRacial biases\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_4_3\" value=\"Gender biases\"/>\nGender biases\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_4_4\" value=\"Language biases, particularly favouring English\"/>\nLanguage biases, particularly favouring English\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_4\"></div>\n</form>\n<script>function validate_form_Q15_4() {var text; var x1 = document.getElementById('answer_Q15_4_1'); var x2 = document.getElementById('answer_Q15_4_2'); var x3 = document.getElementById('answer_Q15_4_3'); var x4 = document.getElementById('answer_Q15_4_4'); if (x1.checked == true&x2.checked == true&x3.checked == true&x4.checked == true){text = 'You are correct, that would be all of them… 😔';} else {text = 'That’s a start but, sadly, there are more biases.';} document.getElementById('result_Q15_4').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4;res1 = document.getElementById('result_Q15_1').innerText == 'That’s right, well done! Click on the tab below to find out a little more about each metaphor.'; res2 = document.getElementById('result_Q15_2').innerText == 'That’s right! ✅'; res3 = document.getElementById('result_Q15_3').innerText == 'Correct!'; res4 = document.getElementById('result_Q15_4').innerText == 'You are correct, that would be all of them… 😔';text = res1 + res2 + res3 + res4;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hint_16911\" onclick=\"return show_hint_16911()\">🦜 Click on the parrot for a hint.</div>\n<div id=\"result_16911\" onclick=\"return show_hint_16911()\"></div>\n<script>function show_hint_16911(){var x = document.getElementById('result_16911').innerHTML; if(!x){document.getElementById('result_16911').innerHTML = 'Jeff Pooley discusses how LLMs can exacerbate existing biases in academia.';} else {document.getElementById('result_16911').innerHTML = '';}}</script>\n```\n\n:::\n:::\n\n:::\n::: {.callout-tip collapse=\"false\"}\n#### Your turn! {.unnumbered}\n\nRead through Google's \"AI overview\" displayed below. Note that you can click on the images to enlarge them.\n\n::::: {#fig-Reddit layout-ncol=\"2\"}\n![Google AI overview to the query \"cheese not sticking to pizza\" from 2024](images/google_cheese.jpg){#fig-alt=\"Google query: 'cheese not sticking to pizza' The AI Overview reads: Here are some tips to help cheese stick to pizza: Mix about 1/8 cup of non-toxic glue, like Elmer's school glue, into the sauce to add some tackiness. Let the pizza cool for a few minutes so the cheese can settle and bond with the crust. Cook the cheese until it just melts, but don't overcook it.\"}\n\n![Satirical [Reddit post](https://www.reddit.com/r/Pizza/comments/1a19s0/comment/c8t7bbp/) from 2013](images/reddit_cheese.png){fig-alt=\"Reddit post by user \\\"fucksmith\\\" dating from 13y ago. The post reads: To get the cheese to stick I recommend mixing about 1/8 cup of Elmer's glue Q in with the sauce. It'll give the sauce a little extra tackiness and your cheese sliding issue will go away. It'll also add a little unique flavor. I like Elmer's school glue, but any glue will work as long as it's non-toxic. The post has 197 replies.\"}\n\nScreenshots from [r/Pizza](https://www.reddit.com/r/Pizza/comments/1a19s0/comment/l58bvc1/) illustrating the infamous 'pizza glue' AI fail [see also @notopoulosGoogleAISaid2024]\n:::::\n\n[**Q15.5**]{style=\"color:green;\"} Among a number of sensible-sounding suggestions, we find a recommendation for adding non-toxic glue to pizza sauce. This mention is thought to have come from an old Reddit post (see screenshot above). Which aspect(s) of the AI overview point to this theory?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_5\" onsubmit=\"return validate_form_Q15_5()\" method=\"post\">\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_5_1\" value=\"The AI overview&#39;s mention of non-toxic glue to the sauce is likely a hallucination.\"/>\nThe AI overview's mention of non-toxic glue to the sauce is likely a hallucination.\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_5_2\" value=\"The format of the AI overview is similar to that of the Reddit post.\"/>\nThe format of the AI overview is similar to that of the Reddit post.\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_5_3\" value=\"Reddit is usually one of the most reliable sources for recipes and cooking tips on the Internet.\"/>\nReddit is usually one of the most reliable sources for recipes and cooking tips on the Internet.\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_5_4\" value=\"The AI overview uses the same, in the context of cooking, unusual word as fucksmith: &#39;tackiness&#39;.\"/>\nThe AI overview uses the same, in the context of cooking, unusual word as fucksmith: 'tackiness'.\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_5_5\" value=\"The AI overview mentions the same quantity of glue as in the Reddit post.\"/>\nThe AI overview mentions the same quantity of glue as in the Reddit post.\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_5_6\" value=\"The AI overview mentions the same type of glue as in the Reddit post.\"/>\nThe AI overview mentions the same type of glue as in the Reddit post.\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_5\"></div>\n</form>\n<script>function validate_form_Q15_5() {var text; var x1 = document.getElementById('answer_Q15_5_1'); var x2 = document.getElementById('answer_Q15_5_2'); var x3 = document.getElementById('answer_Q15_5_3'); var x4 = document.getElementById('answer_Q15_5_4'); var x5 = document.getElementById('answer_Q15_5_5'); var x6 = document.getElementById('answer_Q15_5_6'); if (x1.checked == false&x2.checked == false&x3.checked == false&x4.checked == true&x5.checked == true&x6.checked == true){text = 'Absolutely! ✅';} else {text = 'No, not quite.';} document.getElementById('result_Q15_5').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4, res5;res1 = document.getElementById('result_Q15_1').innerText == 'That’s right, well done! Click on the tab below to find out a little more about each metaphor.'; res2 = document.getElementById('result_Q15_2').innerText == 'That’s right! ✅'; res3 = document.getElementById('result_Q15_3').innerText == 'Correct!'; res4 = document.getElementById('result_Q15_4').innerText == 'You are correct, that would be all of them… 😔'; res5 = document.getElementById('result_Q15_5').innerText == 'Absolutely! ✅';text = res1 + res2 + res3 + res4 + res5;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hint_93648\" onclick=\"return show_hint_93648()\">🦜 Click on the parrot for a hint.</div>\n<div id=\"result_93648\" onclick=\"return show_hint_93648()\"></div>\n<script>function show_hint_93648(){var x = document.getElementById('result_93648').innerHTML; if(!x){document.getElementById('result_93648').innerHTML = 'Three of these reasons are likely to be correct.';} else {document.getElementById('result_93648').innerHTML = '';}}</script>\n```\n\n:::\n:::\n\n:::\n::: {.callout-tip collapse=\"false\"}\n#### Your turn! {.unnumbered}\n\nAs part of an exploratory (not pre-registered) analysis, @tamkin2026 from Anthropic (see @sec-HumanLearning) decomposed the quiz scores into sub-areas and question types (see Figure 8 from @tamkin2026, reprinted below). Each question in the quiz belonged to exactly one task (e.g., Task 1 or Task 2) and exactly one question type (e.g., Conceptual, Debugging, or Code Reading). Figure 8 shows that, for both tasks, the control (no AI) group performed better than the AI group.\n\n[![Figure 8 from @tamkin2026: Score breakdown by questions type relating to each task and skill area](images/Shen_Tamkin2026_Fig8.png){fig-alt=\"A plot showing participants' average scores in each type of quiz questions together with 95% CI error bars. Across all subareas of the quiz (task 1, task 2, conceptual, debugging, and code reading), the control, no AI group performed better on average than the treatment, AI group. However, the 95% CI intervals of the two groups always overlap to a smaller or larger degree. The difference in average scores is largest for the debugging questions and smallest for the code reading.\"}](http://arxiv.org/abs/2601.20245)\n\n[**Q15.6**]{style=\"color:green;\"} Looking at the results displayed in Figure 8 above, which question type shows the largest difference in average quiz scores between the treatment and control groups?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_6\" onsubmit=\"return validate_form_Q15_6()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_Q15_6\" id=\"answer_Q15_6_1\" value=\"Conceptual\"/>\nConceptual\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_6\" id=\"answer_Q15_6_2\" value=\"Debugging\"/>\nDebugging\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_6\" id=\"answer_Q15_6_3\" value=\"Code Reading\"/>\nCode Reading\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_6\"></div>\n</form>\n<script>function validate_form_Q15_6() {var x, text; var x = document.forms['form_Q15_6']['answer_Q15_6'].value;if (x == 'Debugging'){text = 'That’s right! 🎉 The debugging questions show the largest difference between the treatment (AI) and the control (no AI) groups.';} else {text = 'No, that’s not it. Look for the question type with the greatest vertical distance between the treatment (AI) and control (no AI) group averages (represented as dots).';} document.getElementById('result_Q15_6').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4, res5;res1 = document.getElementById('result_Q15_2').innerText == 'That’s right! ✅'; res2 = document.getElementById('result_Q15_3').innerText == 'Correct!'; res3 = document.getElementById('result_Q15_4').innerText == 'You are correct, that would be all of them… 😔'; res4 = document.getElementById('result_Q15_5').innerText == 'Absolutely! ✅'; res5 = document.getElementById('result_Q15_6').innerText == 'That’s right! 🎉 The debugging questions show the largest difference between the treatment (AI) and the control (no AI) groups.';text = res1 + res2 + res3 + res4 + res5;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n\n[**Q15.7**]{style=\"color:green;\"} Why might the control group have, on average, performed better on debugging questions compared to the AI group?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_7\" onsubmit=\"return validate_form_Q15_7()\" method=\"post\">\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_7_1\" value=\"The AI tool was specifically designed to help with debugging, giving the treatment group a clear advantage.\"/>\nThe AI tool was specifically designed to help with debugging, giving the treatment group a clear advantage.\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_7_2\" value=\"The control group had no AI assistance, so they encountered more errors during the task and gained more experience debugging.\"/>\nThe control group had no AI assistance, so they encountered more errors during the task and gained more experience debugging.\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_7_3\" value=\"The debugging questions were easier than the rest, so both groups scored high, and the treatment group only scored slightly higher by chance.\"/>\nThe debugging questions were easier than the rest, so both groups scored high, and the treatment group only scored slightly higher by chance.\n</label>\n<br/>\n<label>\n<input type=\"checkbox\" id=\"answer_Q15_7_4\" value=\"The treatment group had more practice with debugging during the experimental task.\"/>\nThe treatment group had more practice with debugging during the experimental task.\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_7\"></div>\n</form>\n<script>function validate_form_Q15_7() {var text; var x1 = document.getElementById('answer_Q15_7_1'); var x2 = document.getElementById('answer_Q15_7_2'); var x3 = document.getElementById('answer_Q15_7_3'); var x4 = document.getElementById('answer_Q15_7_4'); if (x1.checked == false&x2.checked == true&x3.checked == false&x4.checked == false){text = '✅ This is indeed what the paper states. The authors of the study conclude that, without relying on “AI” help, the control group made more errors and developed stronger debugging skills through experience.';} else {text = 'Not quite. Consider how not having access to “AI” assistance might have led to more hands-on debugging practice.';} document.getElementById('result_Q15_7').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4, res5, res6;res1 = document.getElementById('result_Q15_1').innerText == 'That’s right, well done! Click on the tab below to find out a little more about each metaphor.'; res2 = document.getElementById('result_Q15_2').innerText == 'That’s right! ✅'; res3 = document.getElementById('result_Q15_3').innerText == 'Correct!'; res4 = document.getElementById('result_Q15_4').innerText == 'You are correct, that would be all of them… 😔'; res5 = document.getElementById('result_Q15_5').innerText == 'Absolutely! ✅'; res6 = document.getElementById('result_Q15_7').innerText == '✅ This is indeed what the paper states. The authors of the study conclude that, without relying on “AI” help, the control group made more errors and developed stronger debugging skills through experience.';text = res1 + res2 + res3 + res4 + res5 + res6;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hint_62728\" onclick=\"return show_hint_62728()\">🦜 Click on the parrot for a hint.</div>\n<div id=\"result_62728\" onclick=\"return show_hint_62728()\"></div>\n<script>function show_hint_62728(){var x = document.getElementById('result_62728').innerHTML; if(!x){document.getElementById('result_62728').innerHTML = 'The authors of the study only mention one of these as a possible reason. Which do you think is mostly likely?';} else {document.getElementById('result_62728').innerHTML = '';}}</script>\n```\n\n:::\n:::\n\n\n[**Q15.8**]{style=\"color:green;\"} What do the results displayed in Figure 8 from @tamkin2026 (see above) suggest about the impact of AI assistance on code reading skills?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_8\" onsubmit=\"return validate_form_Q15_8()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_Q15_8\" id=\"answer_Q15_8_1\" value=\"The confidence intervals corresponding to the code reading questions overlap too much to be able to draw any conclusions.\"/>\nThe confidence intervals corresponding to the code reading questions overlap too much to be able to draw any conclusions.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_8\" id=\"answer_Q15_8_2\" value=\"Both groups had similar exposure to reading code through the task, so the AI and non-AI groups performed similarly.\"/>\nBoth groups had similar exposure to reading code through the task, so the AI and non-AI groups performed similarly.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_8\" id=\"answer_Q15_8_3\" value=\"The AI tool significantly improved code reading performance for the treatment group.\"/>\nThe AI tool significantly improved code reading performance for the treatment group.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_8\" id=\"answer_Q15_8_4\" value=\"The control group had more experience reading code, so they scored considerably higher.\"/>\nThe control group had more experience reading code, so they scored considerably higher.\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_8\"></div>\n</form>\n<script>function validate_form_Q15_8() {var x, text; var x = document.forms['form_Q15_8']['answer_Q15_8'].value;if (x == 'Both groups had similar exposure to reading code through the task, so the AI and non-AI groups performed similarly.'){text = 'Indeed, the authors of the study write that the small gap suggests similar exposure and learning in code reading across groups.';} else {text = 'No, the small gap actually implies that AI assistance did not provide a major advantage in this area. Why might that be?';} document.getElementById('result_Q15_8').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4, res5, res6, res7;res1 = document.getElementById('result_Q15_2').innerText == 'That’s right! ✅'; res2 = document.getElementById('result_Q15_3').innerText == 'Correct!'; res3 = document.getElementById('result_Q15_4').innerText == 'You are correct, that would be all of them… 😔'; res4 = document.getElementById('result_Q15_5').innerText == 'Absolutely! ✅'; res5 = document.getElementById('result_Q15_6').innerText == 'That’s right! 🎉 The debugging questions show the largest difference between the treatment (AI) and the control (no AI) groups.'; res6 = document.getElementById('result_Q15_7').innerText == '✅ This is indeed what the paper states. The authors of the study conclude that, without relying on “AI” help, the control group made more errors and developed stronger debugging skills through experience.'; res7 = document.getElementById('result_Q15_8').innerText == 'Indeed, the authors of the study write that the small gap suggests similar exposure and learning in code reading across groups.';text = res1 + res2 + res3 + res4 + res5 + res6 + res7;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n:::\n::: {.callout-tip collapse=\"false\"}\n#### Your turn! {.unnumbered}\n\n[**Q15.9**]{style=\"color:green;\"} What is [Stack Exchange](https://stats.stackexchange.com/)?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_9\" onsubmit=\"return validate_form_Q15_9()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_Q15_9\" id=\"answer_Q15_9_1\" value=\"An online game for learning about programming and statistics, among other topics.\"/>\nAn online game for learning about programming and statistics, among other topics.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_9\" id=\"answer_Q15_9_2\" value=\"An open-source tool for managing project tasks and workflows that is widely used in academic research.\"/>\nAn open-source tool for managing project tasks and workflows that is widely used in academic research.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_9\" id=\"answer_Q15_9_3\" value=\"An open-source social media platform for sharing photos and videos about research and programming.\"/>\nAn open-source social media platform for sharing photos and videos about research and programming.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_9\" id=\"answer_Q15_9_4\" value=\"A free cloud-based service for hosting and managing data and code repositories.\"/>\nA free cloud-based service for hosting and managing data and code repositories.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_9\" id=\"answer_Q15_9_5\" value=\"A network of websites where people can ask and answer questions on a wide range of topics, the most popular of which is StackOverflow for programming questions.\"/>\nA network of websites where people can ask and answer questions on a wide range of topics, the most popular of which is StackOverflow for programming questions.\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_9\"></div>\n</form>\n<script>function validate_form_Q15_9() {var x, text; var x = document.forms['form_Q15_9']['answer_Q15_9'].value;if (x == 'A network of websites where people can ask and answer questions on a wide range of topics, the most popular of which is StackOverflow for programming questions.'){text = 'That’s right! ✅';} else {text = 'No, not quite.';} document.getElementById('result_Q15_9').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4, res5, res6, res7;res1 = document.getElementById('result_Q15_1').innerText == 'That’s right, well done! Click on the tab below to find out a little more about each metaphor.'; res2 = document.getElementById('result_Q15_2').innerText == 'That’s right! ✅'; res3 = document.getElementById('result_Q15_3').innerText == 'Correct!'; res4 = document.getElementById('result_Q15_4').innerText == 'You are correct, that would be all of them… 😔'; res5 = document.getElementById('result_Q15_5').innerText == 'Absolutely! ✅'; res6 = document.getElementById('result_Q15_7').innerText == '✅ This is indeed what the paper states. The authors of the study conclude that, without relying on “AI” help, the control group made more errors and developed stronger debugging skills through experience.'; res7 = document.getElementById('result_Q15_9').innerText == 'That’s right! ✅';text = res1 + res2 + res3 + res4 + res5 + res6 + res7;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hint_25741\" onclick=\"return show_hint_25741()\">🦜 Click on the parrot for a hint.</div>\n<div id=\"result_25741\" onclick=\"return show_hint_25741()\"></div>\n<script>function show_hint_25741(){var x = document.getElementById('result_25741').innerHTML; if(!x){document.getElementById('result_25741').innerHTML = 'Find out more by heading to <a href=\"https://stats.stackexchange.com/\">https://stats.stackexchange.com/</a>.';} else {document.getElementById('result_25741').innerHTML = '';}}</script>\n```\n\n:::\n:::\n\n\n[**Q15.10**]{style=\"color:green;\"} Open this [archived version](https://web.archive.org/web/20260209093908/https://stats.stackexchange.com/questions/11609/clarification-on-interpreting-confidence-intervals) of a Q&A about confidence intervals hosted on Cross Validated, Stack Exchange's statistics forum. In which year did Eliott originally ask their question?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_10\" onsubmit=\"return validate_form_Q15_10()\" method=\"post\">\n<input type=\"text\" placeholder=\"\" name=\"answer_Q15_10\"/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_10\"></div>\n</form>\n<script>function validate_form_Q15_10() {var x, text; var x = document.forms['form_Q15_10']['answer_Q15_10'].value;if (x == '2011'){text = 'Correct! 🎉';} else {text = 'No, not quite.';} document.getElementById('result_Q15_10').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4, res5, res6, res7, res8;res1 = document.getElementById('result_Q15_1').innerText == 'That’s right, well done! Click on the tab below to find out a little more about each metaphor.'; res2 = document.getElementById('result_Q15_2').innerText == 'That’s right! ✅'; res3 = document.getElementById('result_Q15_3').innerText == 'Correct!'; res4 = document.getElementById('result_Q15_4').innerText == 'You are correct, that would be all of them… 😔'; res5 = document.getElementById('result_Q15_5').innerText == 'Absolutely! ✅'; res6 = document.getElementById('result_Q15_7').innerText == '✅ This is indeed what the paper states. The authors of the study conclude that, without relying on “AI” help, the control group made more errors and developed stronger debugging skills through experience.'; res7 = document.getElementById('result_Q15_9').innerText == 'That’s right! ✅'; res8 = document.getElementById('result_Q15_10').innerText == 'Correct! 🎉';text = res1 + res2 + res3 + res4 + res5 + res6 + res7 + res8;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hint_39884\" onclick=\"return show_hint_39884()\">🦜 Click on the parrot for a hint.</div>\n<div id=\"result_39884\" onclick=\"return show_hint_39884()\"></div>\n<script>function show_hint_39884(){var x = document.getElementById('result_39884').innerHTML; if(!x){document.getElementById('result_39884').innerHTML = 'Visit the linked Q&amp;A page on Cross Validated and scroll to the bottom of the first post to find out a) when the question was last edited and b) when it was first asked.';} else {document.getElementById('result_39884').innerHTML = '';}}</script>\n```\n\n:::\n:::\n\n\n[**Q15.11**]{style=\"color:green;\"} As of 9 February 2026 when the page was archived, how many Cross Validated members had upvoted the top answer?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_11\" onsubmit=\"return validate_form_Q15_11()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_Q15_11\" id=\"answer_Q15_11_1\" value=\"34 members\"/>\n34 members\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_11\" id=\"answer_Q15_11_2\" value=\"28 members\"/>\n28 members\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_11\" id=\"answer_Q15_11_3\" value=\"30 members\"/>\n30 members\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_11\" id=\"answer_Q15_11_4\" value=\"32 members\"/>\n32 members\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_11\"></div>\n</form>\n<script>function validate_form_Q15_11() {var x, text; var x = document.forms['form_Q15_11']['answer_Q15_11'].value;if (x == '32 members'){text = '✅';} else {text = 'No, not quite.';} document.getElementById('result_Q15_11').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4, res5, res6, res7, res8, res9;res1 = document.getElementById('result_Q15_1').innerText == 'That’s right, well done! Click on the tab below to find out a little more about each metaphor.'; res2 = document.getElementById('result_Q15_2').innerText == 'That’s right! ✅'; res3 = document.getElementById('result_Q15_3').innerText == 'Correct!'; res4 = document.getElementById('result_Q15_4').innerText == 'You are correct, that would be all of them… 😔'; res5 = document.getElementById('result_Q15_5').innerText == 'Absolutely! ✅'; res6 = document.getElementById('result_Q15_7').innerText == '✅ This is indeed what the paper states. The authors of the study conclude that, without relying on “AI” help, the control group made more errors and developed stronger debugging skills through experience.'; res7 = document.getElementById('result_Q15_9').innerText == 'That’s right! ✅'; res8 = document.getElementById('result_Q15_10').innerText == 'Correct! 🎉'; res9 = document.getElementById('result_Q15_11').innerText == '✅';text = res1 + res2 + res3 + res4 + res5 + res6 + res7 + res8 + res9;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hint_37069\" onclick=\"return show_hint_37069()\">🦜 Click on the parrot for a hint.</div>\n<div id=\"result_37069\" onclick=\"return show_hint_37069()\"></div>\n<script>function show_hint_37069(){var x = document.getElementById('result_37069').innerHTML; if(!x){document.getElementById('result_37069').innerHTML = 'Look for the number next to the up arrow in the top-left corner of the answer.';} else {document.getElementById('result_37069').innerHTML = '';}}</script>\n```\n\n:::\n:::\n\n\n \n\nIn @sec-ttest, we conducted the following *t*-test to find out whether the observed difference between the L1 and L2 speakers' non-verbal IQ 'Blocks' test scores was significant or not:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(formula = Blocks ~ Group, \n       data = Dabrowska.data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Blocks by Group\nt = -4.4084, df = 152.46, p-value = 1.956e-05\nalternative hypothesis: true difference in means between group L1 and group L2 is not equal to 0\n95 percent confidence interval:\n -5.239791 -1.996693\nsample estimates:\nmean in group L1 mean in group L2 \n        13.84444         17.46269 \n```\n\n\n:::\n:::\n\n\nThe output of the `t.test()` command above was fed into an LLM (DeepSeek R1 Distill Llama 70B) with a prompt requesting a short paragraph interpreting these results. The model's response is printed below:\n\n> The Welch two‑sample t‑test shows a significant difference between the groups (t = ‑4.41, df ≈ 152.5, p = 1.96 × 10⁻⁵). Group L1 has a mean of 13.84 blocks, while group L2’s mean is 17.46 blocks, a mean difference of ‑3.62 blocks. The 95 % confidence interval for this difference (‑5.24 to ‑1.99) means we can be 95 % confident that the true average in L2 exceeds that in L1 by roughly 2 to 5 blocks. Because the interval does not include zero, the null hypothesis of equal means is rejected.\n\n[**Q15.12**]{style=\"color:green;\"} Aside from the fact that \"blocks\" is not the correct measurement unit, which major statistical error does the LLM's interpretation of the *t*-test output include?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<form name=\"form_Q15_12\" onsubmit=\"return validate_form_Q15_12()\" method=\"post\">\n<label>\n<input type=\"radio\" name=\"answer_Q15_12\" id=\"answer_Q15_12_1\" value=\"The confidence interval is incorrectly interpreted as a probability statement about the true mean difference across the full population.\"/>\nThe confidence interval is incorrectly interpreted as a probability statement about the true mean difference across the full population.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_12\" id=\"answer_Q15_12_2\" value=\"The mean difference should be positive, not negative, since L2 speakers have a higher mean.\"/>\nThe mean difference should be positive, not negative, since L2 speakers have a higher mean.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_12\" id=\"answer_Q15_12_3\" value=\"The LLM failed to recognise that the t-test was inappropriate because the data are not normally distributed.\"/>\nThe LLM failed to recognise that the t-test was inappropriate because the data are not normally distributed.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_12\" id=\"answer_Q15_12_4\" value=\"The t-test output makes a statement about the alternative hypothesis, not the null hypothesis.\"/>\nThe t-test output makes a statement about the alternative hypothesis, not the null hypothesis.\n</label>\n<br/>\n<label>\n<input type=\"radio\" name=\"answer_Q15_12\" id=\"answer_Q15_12_5\" value=\"The p-value is incorrectly interpreted and is in fact too large to reject the null hypothesis.\"/>\nThe p-value is incorrectly interpreted and is in fact too large to reject the null hypothesis.\n</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_Q15_12\"></div>\n</form>\n<script>function validate_form_Q15_12() {var x, text; var x = document.forms['form_Q15_12']['answer_Q15_12'].value;if (x == 'The confidence interval is incorrectly interpreted as a probability statement about the true mean difference across the full population.'){text = 'That’s right, the 95% confidence interval does not mean that there’s a 95% probability that the true difference lies in that range! 🤯 This is a frequent misconception of confidence intervals that is debunked in the Stack Exchange post that you looked at for earlier quiz questions. Rather, it means that, if we repeated the study many times, 95% of such intervals would contain the true difference.';} else {text = 'No, that’s not it. Consider what confidence intervals represent. This is explained in the Stack Exchange post examined as part of the quiz questions above.';} document.getElementById('result_Q15_12').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4, res5, res6, res7, res8, res9, res10, res11;res1 = document.getElementById('result_Q15_2').innerText == 'That’s right! ✅'; res2 = document.getElementById('result_Q15_3').innerText == 'Correct!'; res3 = document.getElementById('result_Q15_4').innerText == 'You are correct, that would be all of them… 😔'; res4 = document.getElementById('result_Q15_5').innerText == 'Absolutely! ✅'; res5 = document.getElementById('result_Q15_6').innerText == 'That’s right! 🎉 The debugging questions show the largest difference between the treatment (AI) and the control (no AI) groups.'; res6 = document.getElementById('result_Q15_7').innerText == '✅ This is indeed what the paper states. The authors of the study conclude that, without relying on “AI” help, the control group made more errors and developed stronger debugging skills through experience.'; res7 = document.getElementById('result_Q15_8').innerText == 'Indeed, the authors of the study write that the small gap suggests similar exposure and learning in code reading across groups.'; res8 = document.getElementById('result_Q15_9').innerText == 'That’s right! ✅'; res9 = document.getElementById('result_Q15_10').innerText == 'Correct! 🎉'; res10 = document.getElementById('result_Q15_11').innerText == '✅'; res11 = document.getElementById('result_Q15_12').innerText == 'That’s right, the 95% confidence interval does not mean that there’s a 95% probability that the true difference lies in that range! 🤯 This is a frequent misconception of confidence intervals that is debunked in the Stack Exchange post that you looked at for earlier quiz questions. Rather, it means that, if we repeated the study many times, 95% of such intervals would contain the true difference.';text = res1 + res2 + res3 + res4 + res5 + res6 + res7 + res8 + res9 + res10 + res11;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n:::\n:::\n\n:::\n### Check your progress 🌟 {.unnumbered}\n\nCongratulations, you have reached the end of this textbook! In this concluding chapter, you have answered [`<span id=\"checkdown_final_score\">0</span>`{=html} out of 12 questions]{style=\"color:green;\"} correctly. Check out the [Next-step resources](https://elenlefoll.github.io/RstatsTextbook/A_FurtherResources.html) to continue your learning journey!\n\n![Happy learning and good luck with all your data analysis p`R`ojects!️ (artwork by [Allison Horst](https://allisonhorst.com/r-packages-functions) [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/))](images/AHorst_RFlowers.png){fig-alt=\"Two cute little monsters decorating the R logo with hearts, flowers, and smilies.\"}\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}