{
  "hash": "db284a651f06e4f3afea7e68b6d71e0e",
  "result": {
    "engine": "knitr",
    "markdown": "---\nauthor: \"Rose Hörsting & Gina Reinhard\"\ndate: \"2024-11-12\"\n#date-modified: \"2024-11-12\"\ntoc-title: \"Case study: The semantics of emojis\"\ninclude-after-body: abbrv_toc.html\nlanguage: \n  #title-block-modified: \"Last updated\"\n  title-block-author-single: \"Authors\"\n---\n\n\n\n\n# The semantics of emojis: Explo`R`ing the results of an experimental study\n\n\n\n\n\n\n\n\n\n\n\n::: {.callout-note collapse=\"true\"}\n#### **About the authors of this chapter** {.unnumbered}\n\n**Rose Hörsting** is a second-year master’s student in linguistics at the University of Cologne. She completed her bachelor’s degree in linguistics at the Heinrich Heine University Düsseldorf, where she specialised in psycho- and neurolinguistics. Rose is particularly drawn to understanding language processing in both human and machine contexts. She was first introduced to `R` during her bachelor’s thesis, finding it intimidating at first, but has since developed an enthusiasm for statistics and programming. Now, Rose is enjoying the process of mastering `R` as she deepens her skills in data analysis.\n\n**Gina Reinhard** is also a second-year student in the master's programme in linguistics at the University of Cologne, specialising in computational linguistics. Like Rose, she completed her bachelor's degree at Heinrich Heine University Düsseldorf, with a focus on foreign languages and linguistic diversity. Her background includes studying psychology at Osnabrück University and working at an AI company, which led to her interest in all things cognitive science as a combination of linguistics, psychology, and AI. She is currently working as a research assistant in the field of variational linguistics, studying dialects and regiolects while developing her skills in computational methods for linguistic analysis.\n\nThe authors made equal contributions to the chapter and are listed here in alphabetical order. Rose and Gina submitted an earlier version of this chapter as a term paper for Elen Le Foll's M.A. seminar \"More than counting words: Introduction to statistics and data visualisation in R\" (University of Cologne, summer 2024). Elen supervised the project, provided extensive feedback, and contributed to the revisions necessary for publication in this textbook.\n:::\n\n### Chapter overview {.unnumbered}\n\nThis case-study chapter will guide you through the steps to reproduce selected results from a published experimental linguistics study [@fricke2024semantic] using `R`.\n\nThe chapter will walk you through how to:\n\n-   Explore the data of a published linguistics study\n-   Preprocess the raw data for analysis (including how to translate, re-order, and re-categorise the levels of categorical variables)\n-   Analyse and interpret the frequency counts of categorical variables\n-   Visualise these frequencies as barplots\n-   Insert and display emojis in `R` and in `ggplot` graphs\n-   Combine multiple plots into one figure using {patchwork}\n-   Interpret multi-panel plots\n\nWe will work with the original raw data from:\n\n> Fricke, L., Grosz, P. G., & Scheffler, T. (2024). Semantic differences in visually similar face emojis. Language and Cognition, 1–15. <https://doi.org/10.1017/langcog.2024.12>\n\n## Introducing the study 🙂 {#sec-introducing-the-study}\n\nFace emojis are frequently used in text messages. They represent facial expressions and often make fundamental contributions to the subtext of a text message. A few studies have investigated the relationship between emojis and the emotions that they depict [@fugate2021implications; @maier2023emojis; @pfeifer2022all]. However, as emojis are a relatively recent phenomenon, there is still a lot to be discovered. In this chapter, we will look into a study by @fricke2024semantic.\n\n### Deconstructing emojis into Action Units {#sec-deconstructing}\n\n@fricke2024semantic compared \"visually similar face emojis\" using an annotation system developed by @fugate2021implications. This system is based on the Facial Action Coding System (FACS) for human faces [@ekman1978facial]. @fricke2024semantic assigned numbers to human-like facial features such as *eyebrows arched* and *eyes wide*. These numbers are called Action Units, short AUs. As you can see in @fig-emojipairs, each emoji consists of several AUs.\n\n![Emoji pairs and their AU codes [from @fricke2024semantic: 5, CC-BY]](images/CS_RoseGina_emoji_pairs.png){#fig-emojipairs fig-align=\"center\" width=\"700\"}\n\n@fricke2024semantic defined two different types of emoji pairs: In the **AU+ condition**, the pairs of emojis are similar, but are assigned a different set of AUs. The emoji pairs in the **AU- condition** are also similar, but their AUs are identical. AUs capture facial expressions by numbers and, as such, can assist linguists to accurately describe emojis. However, only expressions that can be consciously changed by humans receive number-labels: For example, the AU difference between 😃 and 😆 captures the fact that the former emoji has open eyes while the latter has closed eyes. Since humans can choose whether to open or close their eyes, this is an **AU+ pair**. If the subtle difference between emojis is not manipulable, as in 😄 and 😁, the emojis are described by identical numbers (**AU-**).\n\n### The experiment {#sec-design}\n\n::: {.callout-note title=\"How did the experiment work?\"}\nThree AU+ and three AU- emoji pairs were created (see @fig-emojipairs). Each pair was assigned two contexts, with each context corresponding to the prominent usage of one emoji, but not the other. For example, the contexts of the first pair are *happiness* and *(cheeky) laughter*. The contexts were assigned based on <https://emojipedia.org> and a previous norming study [@scheffler2024affective].\n\nFour single-sentence narratives were created for each of the contexts (see @fig-testitems, translated from German below [translation @fricke2024semantic: 6]).\n\n> 1.  Alex writes to his best friend Stefan:\n>\n>     *I just learned that my cousin's dog has his own advent calendar.*\n>\n>     Alex is amused. Which of the emojis matches the message better? 😄😁\n>\n>     <br>\n>\n> 2.  Alex writes to his best friend Stefan:\n>\n>     *I just learned that I won 500 Euro in the lottery.*\n>\n>     Alex is overjoyed. Which of the emojis matches the message better? 😄😁\n\n![Example of a test item in the experiment [from @fricke2024semantic: 6, CC-BY]](images/CS_RoseGina_Fricke_test_items.png){#fig-testitems fig-align=\"center\" width=\"500\"}\n\nThese short narratives were divided up into into four experimental lists of 12 items. Each list also contained 12 filler items, so that each participant saw 24 items. The participants were then asked to help choose the emoji that best matched the context. Each participant saw each emoji pair twice. It was measured how often participants chose the context-matching emoji versus the non-matching emoji.\n:::\n\n@fricke2024semantic's central research question was: **Do AU differences lead to differences in meaning between the two emojis of a pair?** In line with the pictorial approach by @maier2023emojis the authors predicted that visual differences between emojis which correspond to human facial features (AU+) would be more semantically relevant than those that do not (AU-).\n\n::: callout-tip\n#### Quiz time! {.unnumbered}\n\nRead the abstract of the study:\n\n> Fricke, L., Grosz, P. G., & Scheffler, T. (2024). Semantic differences in visually similar face emojis. Language and Cognition, 1–15. <https://doi.org/10.1017/langcog.2024.12>\n\n[**Q1.**]{style=\"color:green;\"} According to the abstract, what were the results of @fricke2024semantic's experiment?\n\n\n\n\n\n```{=html}\n<form name=\"form_43136\" onsubmit=\"return validate_form_43136()\" method=\"post\">\n<input type=\"checkbox\" id=\"answer_43136_1\" value=\"There were no significant differences between the two conditions.\"/>\n<label>There were no significant differences between the two conditions.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_43136_2\" value=\"For both types of pairs, the context-matching emoji was preferred over the non-matching one.\"/>\n<label>For both types of pairs, the context-matching emoji was preferred over the non-matching one.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_43136_3\" value=\"Participants chose the context-matching emoji more often in the AU- condition.\"/>\n<label>Participants chose the context-matching emoji more often in the AU- condition.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_43136_4\" value=\"Participants chose the context-matching emoji more often in the AU+ condition.\"/>\n<label>Participants chose the context-matching emoji more often in the AU+ condition.</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_43136\"></div>\n</form>\n<script>function validate_form_43136() {var text; var x1 = document.getElementById('answer_43136_1'); var x2 = document.getElementById('answer_43136_2'); var x3 = document.getElementById('answer_43136_3'); var x4 = document.getElementById('answer_43136_4'); if (x1.checked == true&x2.checked == true&x3.checked == false&x4.checked == false){text = 'That’s right!';} else {text = 'Not quite. Read the abstract again.';} document.getElementById('result_43136').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1;res1 = document.getElementById('result_43136').innerText == 'That’s right!';text = res1;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n\n\n\n \n\n[**Q2.**]{style=\"color:green;\"} The actual results of the experiment were different from what @fricke2024semantic had expected. According to author's research hypothesis (visual differences between emojis which correspond to human facial features are more semantically relevant than those that do not), which of these experimental results were expected?\n\n\n\n\n\n```{=html}\n<form name=\"form_76455\" onsubmit=\"return validate_form_76455()\" method=\"post\">\n<input type=\"checkbox\" id=\"answer_76455_1\" value=\"Participants will choose the context-matching emoji more often in the AU- condition.\"/>\n<label>Participants will choose the context-matching emoji more often in the AU- condition.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_76455_2\" value=\"For both types of pairs, the context-matching emoji will be preferred over the non-matching one.\"/>\n<label>For both types of pairs, the context-matching emoji will be preferred over the non-matching one.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_76455_3\" value=\"Participants will choose the context-matching emoji more often in the AU+ condition.\"/>\n<label>Participants will choose the context-matching emoji more often in the AU+ condition.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_76455_4\" value=\"For the AU- pairs, the pattern will be more random.\"/>\n<label>For the AU- pairs, the pattern will be more random.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_76455_5\" value=\"For the AU+ pairs, the pattern will be more random.\"/>\n<label>For the AU+ pairs, the pattern will be more random.</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_76455\"></div>\n</form>\n<script>function validate_form_76455() {var text; var x1 = document.getElementById('answer_76455_1'); var x2 = document.getElementById('answer_76455_2'); var x3 = document.getElementById('answer_76455_3'); var x4 = document.getElementById('answer_76455_4'); var x5 = document.getElementById('answer_76455_5'); if (x1.checked == false&x2.checked == false&x3.checked == true&x4.checked == true&x5.checked == false){text = 'That’s right! The hypothesis was that visual differences between emojis would be semantically more relevant if they corresponded to differences in human facial features (AU+). This would lead to participants choosing a context-matching emoji more often in the AU+ condition and making more random choices in the AU- condition.';} else {text = 'Not quite. Try again.';} document.getElementById('result_76455').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2;res1 = document.getElementById('result_43136').innerText == 'That’s right!'; res2 = document.getElementById('result_76455').innerText == 'That’s right! The hypothesis was that visual differences between emojis would be semantically more relevant if they corresponded to differences in human facial features (AU+). This would lead to participants choosing a context-matching emoji more often in the AU+ condition and making more random choices in the AU- condition.';text = res1 + res2;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n```{=html}\n<div id=\"hint_95120\" onclick=\"return show_hint_95120()\">🐭 Click on the mouse for a hint.</div>\n<div id=\"result_95120\" onclick=\"return show_hint_95120()\"></div>\n<script>function show_hint_95120(){var x = document.getElementById('result_95120').innerHTML; if(!x){document.getElementById('result_95120').innerHTML = 'Based on the authors’ hypothesis, differences corresponding to facial features (AU+) would be more semantically relevant. In contrast, differences that do not correspond to facial features (AU-) would be less semantically relevant, making them less noticeable and leading to more inconsistent choices. How might this affect the frequency with which participants choose the context-matching emoji in each condition?';} else {document.getElementById('result_95120').innerHTML = '';}}</script>\n```\n\n\n\n\n<br>\n:::\n\n## Exploring the relationship between gender and emoji understanding {#sec-gender-understanding toc-text=\"Exploring gender and emoji understanding\"}\n\n@fricke2024semantic asked participants about their gender, their attitude towards emojis, how often they use emojis on WhatsApp and how well they think they understand emojis. The authors visualised the distribution of men and women for emoji use and emoji attitude as barplots.\n\n::: {#fig-FrickeGenderBarplots layout-ncol=\"2\"}\n![Emoji use by gender](images/CS_RoseGina_Fricke_emoji_use.png){#fig-emojiuse fig-align=\"center\" width=\"550\"}\n\n![Attitude towards emojis by gender](images/CS_RoseGina_Fricke_emoji_attitude.png){#fig-emojiattitude fig-align=\"center\" width=\"550\"}\n\nBarplots from Fricke, Grosz & Scheffler [-@fricke2024semantic: 9-10, CC-BY]\n:::\n\nThe plots in @fig-FrickeGenderBarplots show that women use emojis more often and have a more positive attitude towards emojis than men. We want to find out whether women also reported a higher level of emoji understanding than men. Our analysis will involve three steps:\n\n1.  Calculating the frequencies of the genders in the data\\\n2.  Calculating the frequencies of the different levels of emoji understanding for each gender\\\n3.  Visualising the frequencies in a barplot similar to the plots above.\n\n### Impo`R`ting the data {#sec-importing-the-data}\n\n@fricke2024semantic have made their data and analysis code publicly available on the OSF repository (see @sec-OpenScience). You can access these materials at <https://osf.io/k2t9p/>. There, the data is stored in the file `raw_data.csv`. To follow the steps of this chapter, you will need to download this file.\n\n::: callout-warning\n### Session set-up {#sec-session-set-up}\n\nTo run the code of this chapter, you will need the following packages. Make sure that they are installed and loaded before starting.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(here)\nlibrary(tidyverse)\n#install.packages(\"patchwork\")\nlibrary(patchwork)\n#install.packages(\"ragg\")\nlibrary(ragg)\n```\n:::\n\n\n\n:::\n\nWe import the authors' raw data using the `read.csv()` and `here()` functions. You will need to adjust the file path to match the folder structure of your computer (see @sec-ImportingDataCSV).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_data <- read.csv(file = here(\"data\", \"raw_data.csv\"))\n```\n:::\n\n\n\n\nAs specified by Fricke, Grosz & Scheffler [-@fricke2024semantic: 8], we filter out participants who exceed the maximum age of 35 years for all following analyses. We do this by using the `filter()` function and store the result in a new data frame called `df`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- raw_data |> \n  filter(age <= 35)\n```\n:::\n\n\n\n\n### Gender frequency analysis {#sec-gender-freq}\n\nLet's first get a general overview: How many men, women, and non-binary people participated in the study?\n\nThe relevant variable in the data set is called `gender`. However, you will see that the names of the gender groups are in German. To figure out what the labels of the different gender groups are, we use the `count()` function:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  count(gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    gender    n\n1   divers   72\n2 männlich 2616\n3 weiblich 1128\n```\n\n\n:::\n:::\n\n\n\n\nBefore we start analysing, we should translate the labels (levels) of the categories into English. Using a combination of `mutate()` and `recode()`, we translate *männlich* to *men*, *weiblich* to *women*, and *divers* to *non-binary.*[^cs_rosegina-1]\n\n[^cs_rosegina-1]: We decided to translate '*divers*' as 'non-binary', as this is the English term that @fricke2024semantic used in their paper.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df |> \n  mutate(gender = recode(gender, \n                         \"männlich\" = \"men\", \n                         \"weiblich\" = \"women\", \n                         \"divers\" = \"non-binary\"))\n\ndf |> \n  count(gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      gender    n\n1        men 2616\n2 non-binary   72\n3      women 1128\n```\n\n\n:::\n:::\n\n\n\n\nNow that `gender` variable have English labels, we want to determine how many male, female, and non-binary subjects participated. We have used the `table()` function, which determines the number of occurrences of the different genders in the data. But in this case counting the occurrences is not straightforward. The data frame contains 24 rows for each subject, as each participant saw 24 items (see @sec-design). So, if we were to simply count the occurrences of *men*, *women*, and *non-binary* in the data with `count()`, we would end up with 24 times the values of the frequencies.\n\nTo determine the actual gender distribution, we need to count the occurrences according to the subjects' unique IDs. To do this, we apply the `distinct()` function to keep only unique occurrences (to be precise, the first unique occurrence) of each `submission_id`. The argument `.keep_all` is set to `TRUE`, which means that all other variables in the data frame are kept and not deleted.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  distinct(submission_id, .keep_all = TRUE) |> \n  count(gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      gender   n\n1        men 109\n2 non-binary   3\n3      women  47\n```\n\n\n:::\n:::\n\n\n\n\nThe **mode** (see @sec-Mode) of the `gender` variable in the dataset is *men*, as you can see from the output. The gender distribution is very uneven: 109 men, 47 women, and 3 non-binary people participated in the study. If we are not careful, this imbalance can lead to misleading data visualisations.\n\n::: callout-tip\n#### Quiz time! {.unnumbered}\n\n[**Q3.**]{style=\"color:green;\"} Which of these problems are likely to occur if we plot emoji understanding by gender in a barplot with unequal gender groups?\n\n\n\n\n\n```{=html}\n<form name=\"form_70272\" onsubmit=\"return validate_form_70272()\" method=\"post\">\n<input type=\"checkbox\" id=\"answer_70272_1\" value=\"It may appear as if men have better emoji understanding simply because of their group size.\"/>\n<label>It may appear as if men have better emoji understanding simply because of their group size.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_70272_2\" value=\"It may appear as if non-binary people have lower emoji understanding simply because of their group size.\"/>\n<label>It may appear as if non-binary people have lower emoji understanding simply because of their group size.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_70272_3\" value=\"We will not be able to use ggplot to visualise the data.\"/>\n<label>We will not be able to use ggplot to visualise the data.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_70272_4\" value=\"The differences in emoji understanding between gender groups may look bigger or smaller than they actually are.\"/>\n<label>The differences in emoji understanding between gender groups may look bigger or smaller than they actually are.</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_70272\"></div>\n</form>\n<script>function validate_form_70272() {var text; var x1 = document.getElementById('answer_70272_1'); var x2 = document.getElementById('answer_70272_2'); var x3 = document.getElementById('answer_70272_3'); var x4 = document.getElementById('answer_70272_4'); if (x1.checked == true&x2.checked == true&x3.checked == false&x4.checked == true){text = 'That’s right! Unequal group sizes can distort the differences by showing larger totals for larger groups and smaller totals for smaller groups. <br><br>Can you think of ways to address this issue?';} else {text = 'Not quite. Try again.';} document.getElementById('result_70272').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3;res1 = document.getElementById('result_43136').innerText == 'That’s right!'; res2 = document.getElementById('result_76455').innerText == 'That’s right! The hypothesis was that visual differences between emojis would be semantically more relevant if they corresponded to differences in human facial features (AU+). This would lead to participants choosing a context-matching emoji more often in the AU+ condition and making more random choices in the AU- condition.'; res3 = document.getElementById('result_70272').innerText == 'That’s right! Unequal group sizes can distort the differences by showing larger totals for larger groups and smaller totals for smaller groups. Can you think of ways to address this issue?';text = res1 + res2 + res3;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n```{=html}\n<div id=\"hint_82474\" onclick=\"return show_hint_82474()\">🐭 Click on the mouse for a hint.</div>\n<div id=\"result_82474\" onclick=\"return show_hint_82474()\"></div>\n<script>function show_hint_82474(){var x = document.getElementById('result_82474').innerHTML; if(!x){document.getElementById('result_82474').innerHTML = 'Three of these problems could occur.';} else {document.getElementById('result_82474').innerHTML = '';}}</script>\n```\n\n\n\n\n<br>\n:::\n\nTo solve this problem, we will use the same strategy as @fricke2024semantic. We will use relative rather than absolute frequencies to make sure that the numbers for the different genders are comparable. This means that we will calculate the percentages of emoji understanding within each gender group, treating the total number of male, female, and non-binary participants separately as 100%, rather than counting all subjects together as 100%. In this way, we can see, for example, what percentage of men, women, and non-binary participants reported a very good emoji understanding and compare the numbers across groups.\n\n### How well do the different genders understand emojis? {#sec-gender-understanding-freq}\n\nNext, we calculate the relative frequencies of the different levels of emoji understanding for each gender.\n\nThe variable we are interested in is called `emoji_understanding`. Just like with `gender`, we first have to do some data wrangling. We use the `count()` function to get the labels:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  count(emoji_understanding)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  emoji_understanding    n\n1            eher gut  912\n2                 gut 1344\n3         mittelmäßig   48\n4            sehr gut 1512\n```\n\n\n:::\n:::\n\n\n\n\nWe translate *mittelmäßig* to *moderate*, *eher gut* to *rather good*, *gut* to *good*, and *sehr gut* to *very good*:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df |> \n    mutate(emoji_understanding = recode(emoji_understanding,\n                                        \"mittelmäßig\" = \"moderate\",\n                                        \"eher gut\" = \"rather good\",\n                                        \"gut\" = \"good\",\n                                        \"sehr gut\" = \"very good\"))\ndf |> \n  count(emoji_understanding)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  emoji_understanding    n\n1                good 1344\n2            moderate   48\n3         rather good  912\n4           very good 1512\n```\n\n\n:::\n:::\n\n\n\n\nThe levels are still in the wrong order. We need to rearrange them in an ascending order from *moderate* to *very good*. To do this, we define a vector `c(\"moderate\", \"rather good\", \"good\", \"very good\")`. Using the `factor()` function, we encode this vector as a factor:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df |> \n    mutate(emoji_understanding = factor(emoji_understanding,\n                                        levels = c(\"moderate\",\n                                                   \"rather good\",\n                                                   \"good\",\n                                                   \"very good\")))\n\ndf |> \n  count(emoji_understanding)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  emoji_understanding    n\n1            moderate   48\n2         rather good  912\n3                good 1344\n4           very good 1512\n```\n\n\n:::\n:::\n\n\n\n\nThe levels now look good, so we can determine the frequencies for the different gender groups within `emoji_understanding`. We could do this by simply cross-tabulating gender with emoji understanding (see @sec-Mode). But since we know that the sizes of the gender subsets are very unequal, we also want to calculate the relative frequencies to make the numbers comparable. There is an easy way to calculate relative frequencies using the `proportions()` function (see @sec-DistCat). However, we need to make two additional considerations:\n\n1.  Our aim is to calculate proportions within groups and not across the whole data.\n2.  We want to create a comprehensive visualisation that includes both groups of men and women in a single barplot.\n\nTo achieve both, we have to first group our data, using the powerful combination of `group_by()` and `count()`. We create a new data frame `gender_understanding_count` and again keep only each participant's unique `submission_id` as above. We group the data by gender and count the frequencies for the different genders within the `emoji_understanding` factor:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  distinct(submission_id, .keep_all = TRUE) |>\n  group_by(gender) |> \n  count(gender, emoji_understanding)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n# Groups:   gender [3]\n   gender     emoji_understanding     n\n   <chr>      <fct>               <int>\n 1 men        moderate                1\n 2 men        rather good            25\n 3 men        good                   41\n 4 men        very good              42\n 5 non-binary rather good             1\n 6 non-binary good                    2\n 7 women      moderate                1\n 8 women      rather good            12\n 9 women      good                   13\n10 women      very good              21\n```\n\n\n:::\n:::\n\n\n\n\nIn this table, `n` was calculated by the `count()` function and represents the number of occurrences for each combination of `gender` and `emoji_understanding`. Next, we use `mutate()` to add a column with the relative frequencies, which we calculate with the formula `proportions(n) * 100` to obtain percentages.\n\n\n\n\n::: {.cell source-line-numbers='5'}\n\n```{.r .cell-code}\ngender_understanding_count <- df |>\n  distinct(submission_id, .keep_all = TRUE) |>\n  group_by(gender) |> \n  count(gender, emoji_understanding) |> \n  mutate(percentage = proportions(n) * 100)\n\ngender_understanding_count\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n# Groups:   gender [3]\n   gender     emoji_understanding     n percentage\n   <chr>      <fct>               <int>      <dbl>\n 1 men        moderate                1      0.917\n 2 men        rather good            25     22.9  \n 3 men        good                   41     37.6  \n 4 men        very good              42     38.5  \n 5 non-binary rather good             1     33.3  \n 6 non-binary good                    2     66.7  \n 7 women      moderate                1      2.13 \n 8 women      rather good            12     25.5  \n 9 women      good                   13     27.7  \n10 women      very good              21     44.7  \n```\n\n\n:::\n:::\n\n\n\n\nThis tabular presentation of the data already shows us that non-binary participants reported either a *rather good* or *good* understanding of emojis. A higher percentage of women (44.7%) reported a *very good* emoji understanding compared to men (38.5%). But let's create our barplot to see the distribution more clearly.\n\n### Data visualisation 📊 {#sec-gender-understanding-vis}\n\nAs mentioned above, we will visualise the relative rather than the absolute frequencies to make sure that the numbers for the different genders are comparable. In line with Fricke, Grosz & Scheffler [-@fricke2024semantic: 9], we also exclude the three non-binary participants. To this end, we use the `filter()` function combined with the `!=` operator (see @sec-RelationalOperators).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngender_understanding_count <- gender_understanding_count |> \n  filter(gender != \"non-binary\")\n```\n:::\n\n\n\n\nWe use `ggplot()` to create a barplot with the `emoji_understanding` categories on the *x*-axis and the relative frequencies that we calculated on the *y*-axis. The bars are coloured according to `gender`. We also add a title and axis labels. Finally, we remove the white space between the bottom of the bars with an additional `scale_y_continuous(expand = c(0,0))` layer and change the colours to make our plot look nicer. The hexadecimal color values chosen here are from the colour-blind friendly palette \"Set2\" from the package [{RColorBrewer}](https://cran.r-project.org/web/packages/RColorBrewer/index.html)[@neuwirth2022package]. Since we only need two colours, we chose to insert them manually to avoid having to install an additional package.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gender_understanding_count, \n       aes(x = emoji_understanding, \n           y = percentage, \n           fill = gender)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  scale_y_continuous(expand = c(0,0)) +\n  labs(title = \"Self-reported Emoji Understanding by Gender\",\n       x = \"Emoji understanding\",\n       y = \"Percent\") +\n  scale_fill_manual(values = c(\"#8DA0CB\", \"#FC8D62\")) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](CS_RoseGina_files/figure-html/gender-understanding-plot-1.png){width=672}\n:::\n:::\n\n\n\n\nAs you can see from the barplot, the gender distribution for emoji understanding is much more even than for emoji use and emoji attitude (see @fig-FrickeGenderBarplots).\n\n::: callout-tip\n#### Quiz time! {.unnumbered}\n\n[**Q4.**]{style=\"color:green;\"} How do you interpret this plot?\n\n\n\n\n\n```{=html}\n<form name=\"form_99672\" onsubmit=\"return validate_form_99672()\" method=\"post\">\n<input type=\"checkbox\" id=\"answer_99672_1\" value=\"Proportionally more women than men reported a very good emoji understanding.\"/>\n<label>Proportionally more women than men reported a very good emoji understanding.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_99672_2\" value=\"Proportionally more women than men reported a moderate emoji understanding.\"/>\n<label>Proportionally more women than men reported a moderate emoji understanding.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_99672_3\" value=\"Around half of all participants reported a rather good understanding of emojis.\"/>\n<label>Around half of all participants reported a rather good understanding of emojis.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_99672_4\" value=\"Women reported a lower level of emoji understanding than men.\"/>\n<label>Women reported a lower level of emoji understanding than men.</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_99672\"></div>\n</form>\n<script>function validate_form_99672() {var text; var x1 = document.getElementById('answer_99672_1'); var x2 = document.getElementById('answer_99672_2'); var x3 = document.getElementById('answer_99672_3'); var x4 = document.getElementById('answer_99672_4'); if (x1.checked == true&x2.checked == true&x3.checked == false&x4.checked == false){text = 'That’s right! While proportionally more women than men reported a very good emoji understanding, a relatively large number of men also stated that they understood emojis very well. There are also proportionally more women than men in the moderate and rather good category. Around 23% of men and 25% of women reported a rather good understanding, but this does not correspond to 50% of participants as there were more men than women in this study.';} else {text = 'Not quite. Try again.';} document.getElementById('result_99672').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4;res1 = document.getElementById('result_43136').innerText == 'That’s right!'; res2 = document.getElementById('result_76455').innerText == 'That’s right! The hypothesis was that visual differences between emojis would be semantically more relevant if they corresponded to differences in human facial features (AU+). This would lead to participants choosing a context-matching emoji more often in the AU+ condition and making more random choices in the AU- condition.'; res3 = document.getElementById('result_70272').innerText == 'That’s right! Unequal group sizes can distort the differences by showing larger totals for larger groups and smaller totals for smaller groups. Can you think of ways to address this issue?'; res4 = document.getElementById('result_99672').innerText == 'That’s right! While proportionally more women than men reported a very good emoji understanding, a relatively large number of men also stated that they understood emojis very well. There are also proportionally more women than men in the moderate and rather good category. Around 23% of men and 25% of women reported a rather good understanding, but this does not correspond to 50% of participants as there were more men than women in this study.';text = res1 + res2 + res3 + res4;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n```{=html}\n<div id=\"hint_92764\" onclick=\"return show_hint_92764()\">🐭 Click on the mouse for a hint.</div>\n<div id=\"result_92764\" onclick=\"return show_hint_92764()\"></div>\n<script>function show_hint_92764(){var x = document.getElementById('result_92764').innerHTML; if(!x){document.getElementById('result_92764').innerHTML = 'Two of the above options are correct interpretations of the plot.';} else {document.getElementById('result_92764').innerHTML = '';}}</script>\n```\n\n\n\n\n<br>\n:::\n\nWhen comparing our barplot to @fig-FrickeGenderBarplots, it is interesting to note that, whilst women reported more frequent use of emojis and a more positive attitude towards emojis, they did not report a higher understanding of emojis. It is possible that some women were more modest in rating their understanding of emojis than men, which could indicate a gender confidence gap. Reporting a good understanding likely requires more confidence compared to emoji use or attitude towards emoji.\n\n## Comparing matching rates between AU conditions {#sec-au-plot}\n\nWe will now turn to exploring the central research question of @fricke2024semantic: **Do AU differences lead to differences in meaning between the two emojis of a pair?** As explained in @sec-deconstructing, AUs are numbers which correspond to human-like facial features. In emoji pairs of the AU+ condition, the visual difference between the emojis is reflected in a number difference, e.g. *grinning face with big eyes* 😃 (AU: **5** + 12 + 25 + 26) and *grinning squinting face* 😆 (AU: 12 + 25 + 26 + **43**). In the AU- condition, the visual difference does not correspond to an AU difference, e.g. *grinning face with smiling eyes* 😄 and *beaming face with smiling eyes* 😁 both have the same AU (12 + 25 + 26 + 63).\n\nStep by step, we will build an informative plot which will include all the information needed to answer this question. This plot will display how many times each emoji was chosen in its presumed corresponding context.\n\nTo achieve this, we need to create a variable that tells us when each participant responded with the matching emoji. In the following, we will create this variable based on the raw data from @fricke2024semantic.\n\n### Preprocessing the data {#sec-au-data-preparation}\n\nFirst, we need a variable that includes the experimental conditions of each trial. The variable `name` tells us whether a trial consisted of an emoji pair with an AU difference (AU+) or not (AU-), or a filler. Trials with AU+ differences include \"AU\" in the trial `name`, those with no AU difference begin with \"N\", and the fillers with \"filler\".\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  distinct(name)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n              name\n1     filler-party\n2         AU-23-L1\n3   filler-heizung\n4         AU-40-L1\n5  filler-schlafen\n6     filler-krank\n7          N-04-L1\n8   filler-friseur\n9          N-37-L1\n10   filler-zombie\n```\n\n\n:::\n:::\n\n\n\n\nWe use a combination of `mutate()`, `case_when()` and `str_detect()` to construct a new variable (`AU_difference`) that captures the type of trial that we are dealing with. The command essentially says: look for the string \"AU\" in the column `name`, and in all cases where you find it (`case_when()`), insert the value \"AU+\" in a new column called `AU_difference`. We follow this procedure for the other trial conditions, too. If neither \"AU\", \"N\" or \"filler\" is detected, nothing (`NULL`) is inserted in `AU_difference`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df |> \n  mutate(AU_difference = case_when(str_detect(name, \"AU\") ~ \"AU+\",\n                                   str_detect(name, \"N\") ~ \"AU-\",\n                                   str_detect(name, \"filler\") ~ \"filler\",\n                                   .default = NULL))\n```\n:::\n\n\n\n\nWe use `select()` to compare the two columns and check that everything worked.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  slice(1:10) |> \n  select(name, AU_difference)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              name AU_difference\n1     filler-party        filler\n2         AU-23-L1           AU+\n3   filler-heizung        filler\n4         AU-40-L1           AU+\n5  filler-schlafen        filler\n6     filler-krank        filler\n7          N-04-L1           AU-\n8   filler-friseur        filler\n9          N-37-L1           AU-\n10   filler-zombie        filler\n```\n\n\n:::\n:::\n\n\n\n\nThis looks promising. Since we are only interested in the experimental items, we now filter out all filler trials.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df |>\n  filter(AU_difference != \"filler\")\n```\n:::\n\n\n\n\nWe will now create another variable called `context`. The column of this variable will contain the context descriptions used by Fricke, Grosz & Scheffler [-@fricke2024semantic: 5] in @fig-emojipairs. Again, we combine `mutate()`, `case_when()` and `str_detect()`: In the `question` column, we look for context-characteristic strings, and add the context descriptions whenever we have a match. Again, we check the output with `table()`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df |> \n  mutate(context = case_when(str_detect(question, \"freut sich\") ~ \"happiness\",\n                             str_detect(question, \"lacht\") ~ \"(cheeky) laughter\",\n\n                             str_detect(question, \"macht sich Sorgen\") ~ \"concern\",\n                             str_detect(question, \"ist überrascht\") ~ \"surprise\",\n                             str_detect(question, \"ist etwas genervt\") ~ \"mild irritation\",\n                             str_detect(question, \"ärgert sich\") ~ \"annoyance\",\n                             str_detect(question, \"amüsiert sich\") ~ \"amusement\",\n                             str_detect(question, \"ist überglücklich\") ~ \"(intense) happiness\",\n                             str_detect(question, \"ist enttäuscht\") ~ \"mild disappointment\",\n                             str_detect(question, \"ist enttäuscht\") ~ \"moderate disappointment\",\n                             str_detect(question, \"ist gut gelaunt\") ~ \"happiness2\",\n                             str_detect(question, \"ist verlegen\") ~ \"bashfulness\",\n                                   .default = NULL))\n\n\ntable(df$context)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  (cheeky) laughter (intense) happiness           amusement           annoyance \n                159                 159                 159                 159 \n        bashfulness             concern           happiness          happiness2 \n                159                 159                 159                 159 \nmild disappointment     mild irritation            surprise \n                318                 159                 159 \n```\n\n\n:::\n:::\n\n\n\n\n::: callout-tip\n#### Quiz time! {.unnumbered}\n\n[**Q5.**]{style=\"color:green;\"} Which problems become apparent when checking the content of our new `context` variable using the `table()` function?\n\n\n\n\n\n```{=html}\n<form name=\"form_95497\" onsubmit=\"return validate_form_95497()\" method=\"post\">\n<input type=\"checkbox\" id=\"answer_95497_1\" value=\"There are more contexts in the output than we coded for.\"/>\n<label>There are more contexts in the output than we coded for.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_95497_2\" value=\"The context descriptions were not correctly assigned in the case of matching strings.\"/>\n<label>The context descriptions were not correctly assigned in the case of matching strings.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_95497_3\" value=\"There are too many occurrences of matches per context than can reasonably be assumed.\"/>\n<label>There are too many occurrences of matches per context than can reasonably be assumed.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_95497_4\" value=\"All contexts have 159 occurrences, except for mild disappointment which occurs 318 times.\"/>\n<label>All contexts have 159 occurrences, except for mild disappointment which occurs 318 times.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_95497_5\" value=\"There are fewer contexts in the output than we coded for\"/>\n<label>There are fewer contexts in the output than we coded for</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_95497\"></div>\n</form>\n<script>function validate_form_95497() {var text; var x1 = document.getElementById('answer_95497_1'); var x2 = document.getElementById('answer_95497_2'); var x3 = document.getElementById('answer_95497_3'); var x4 = document.getElementById('answer_95497_4'); var x5 = document.getElementById('answer_95497_5'); if (x1.checked == false&x2.checked == false&x3.checked == false&x4.checked == true&x5.checked == false){text = 'That’s right! Something must have gone wrong. As you can see, it is always a good idea to check the output of every step of your code for inconsistencies!';} else {text = 'Not quite, try again.';} document.getElementById('result_95497').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4, res5;res1 = document.getElementById('result_43136').innerText == 'That’s right!'; res2 = document.getElementById('result_76455').innerText == 'That’s right! The hypothesis was that visual differences between emojis would be semantically more relevant if they corresponded to differences in human facial features (AU+). This would lead to participants choosing a context-matching emoji more often in the AU+ condition and making more random choices in the AU- condition.'; res3 = document.getElementById('result_70272').innerText == 'That’s right! Unequal group sizes can distort the differences by showing larger totals for larger groups and smaller totals for smaller groups. Can you think of ways to address this issue?'; res4 = document.getElementById('result_99672').innerText == 'That’s right! While proportionally more women than men reported a very good emoji understanding, a relatively large number of men also stated that they understood emojis very well. There are also proportionally more women than men in the moderate and rather good category. Around 23% of men and 25% of women reported a rather good understanding, but this does not correspond to 50% of participants as there were more men than women in this study.'; res5 = document.getElementById('result_95497').innerText == 'That’s right! Something must have gone wrong. As you can see, it is always a good idea to check the output of every step of your code for inconsistencies!';text = res1 + res2 + res3 + res4 + res5;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n\n\n:::\n\nThe contexts *mild disappointment* and *moderate disappointment* have created some issues: In the `question` variable, both are described as *ist enttäuscht* ('is disappointed'). Except for their encoding in the `name` variable, these contexts appear to be identical. At this point, we have no choice but to look for additional disambiguating information in @fricke2024semantic's analysis script, which you can access at <https://osf.io/k8dtp>. The relevant information can be found in lines 522 and 523 (see @fig-script).\n\n![Screenshot from the authors' analysis script available at <https://osf.io/k8dtp>](images/CS_RoseGina_disappointment_script_fricke.png){#fig-script fig-align=\"center\" width=\"600\"}\n\nThe emoji 🙁 (*mild disappointment*) is coded as `N-36` and ☹️ (*moderate disappointment*) as `N-37`. We use this information to assign these two contexts to our `context` variable.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df |> \n  mutate(context = case_when(\n                             str_detect(name, \"N-36\") ~ \"mild disappointment\",\n                             str_detect(name, \"N-37\") ~ \"moderate disappointment\",\n                                   .default = context))\n\ntable(df$context)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      (cheeky) laughter     (intense) happiness               amusement \n                    159                     159                     159 \n              annoyance             bashfulness                 concern \n                    159                     159                     159 \n              happiness              happiness2     mild disappointment \n                    159                     159                     159 \n        mild irritation moderate disappointment                surprise \n                    159                     159                     159 \n```\n\n\n:::\n:::\n\n\n\n\nFinally, we add the critical variable that describes whether there is a match between the chosen emojis and the contexts: if the emoji and the context agree, the variable will have the value *match*. Otherwise, the value will be *no match*.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- df |> \n  mutate(\n  match = case_when(\n    context == \"happiness\" & response == \"grinning_face_with_big_eyes\" ~ \"match\",\n    context == \"(cheeky) laughter\" & response == \"grinning_squinting_face\" ~ \"match\",\n    context == \"concern\" & response == \"hushed_face\" ~ \"match\",\n    context == \"surprise\" & response == \"astonished_face\" ~ \"match\",\n    context == \"mild irritation\" & response == \"neutral_face\" ~ \"match\",\n    context == \"annoyance\" & response == \"expressionless_face\" ~ \"match\",\n    context == \"amusement\" & response == \"grinning_face_with_smiling_eyes\" ~ \"match\",\n    context == \"(intense) happiness\" & response == \"beaming_face_with_smiling_eyes\" ~ \"match\",\n    context == \"mild disappointment\" & response == \"slightly_frowning_face\" ~ \"match\",\n    context == \"moderate disappointment\" & response == \"frowning_face\" ~ \"match\",\n    context == \"happiness2\" & response == \"smiling_face_with_smiling_eyes\" ~ \"match\",\n    context == \"bashfulness\" & response == \"smiling_face\" ~ \"match\",\n    .default = \"no match\"))\n```\n:::\n\n\n\n\n### Building the plots {#sec-au-plot-building}\n\nWe will now build our plots to visualise the matching rates per emoji pair. In a new table called `data_AU`, we group the data by contexts. The command `count(match)` counts matches and non-matches for each context and stores them in a new column called `n`. We add the column `percent` to store the rounded percentage of matches and non-matches for each context-pair.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_AU <- df |> \n  group_by(context) |> \n  count(match) |>\n  mutate(percent = round(proportions(n)*100, 2))\n```\n:::\n\n\n\n\nUsing the `View()` function, we take a look at our data.\n\n![The first 14 columns of the data frame data_AU as visualised using the `View()` function in RStudio](images/CS_RoseGina_context_percentages.png){#fig-data-percentages fig-align=\"center\" width=\"400\"}\n\nWe plot the first emoji pair of the AU+ condition 😯 😲 with their respective contexts *concern* and *surprise.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nplot_concern_surprise <- data_AU |> \n  filter(context == \"concern\" | context == \"surprise\") |>\n  ggplot(aes(x = context, y = percent, fill = match)) +\n  geom_col() +\n  scale_x_discrete(limits = c(\"concern\", \"surprise\")) +\n  scale_y_continuous(expand = c(0,0)) +\n  scale_fill_manual(values = c(\"#66C2A5\", \"#E78AC3\")) +\n  geom_text(aes(label = percent), position = position_stack(vjust = 0.5)) +\n  labs(title = \"😯 😲\", x = \"\") +\n  theme_classic() +\n  theme(plot.title = element_text(hjust = 0.5, size = 20), \n        legend.title=element_blank())\n```\n:::\n\n\n\n\nThe code above creates a barplot and stores it in `plot_concern_surprise`. Here's what each line of code does:\n\n1.  Begin by assigning a clear name for the plot and call the data to be plotted.\n2.  Filter the contexts, such that only rows of the contexts *concern* or (`|`) *surprise* are plotted.\n3.  Create a `ggplot` object with the context values on the *x*-axis and percentages on the *y*-axis. Colours are filled corresponding to the match values.\n4.  Display the data as a barplot. By default, `geom_bar()` counts how many times *match* and *no match* occur. However, as we have already calculated and stored the values in the column `percent`, we use `geom_col()` to be able to use the data as is.\n5.  The context values, which are displayed on the *x*-axis, are discrete. With this command, we set and order the contexts.\n6.  Use the \"expand\" argument of the `scale_y_continuous()` function to remove the white space between the bars and the *x*-axis.\n7.  Adjust colours with values from \"Set2\" from the {RColorBrewer} package (see @sec-gender-understanding-vis).\n8.  Annotate the percentages of matching rates by adding them as text and placing them inside the plot, in the middle of the corresponding bars.\n9.  Add the corresponding emojis at the top of the plot and remove the superfluous *x-*axis label \"context\".\n10. Add a theme, in this case `theme_classic()`.\n11. Plots are left-aligned by default. Since we want the emojis to be displayed on top of their corresponding context bars, we move the title to the centre of the plot. To ensure that the emojis are easily interpretable, we also increase the font size to 20 points.\n12. Finally, we remove the title of the legend because the *match* and *no match* values are self-explanatory.\n\nLet's take a look at our plot. It's looking great, but we don't need just one plot, we need six: one for each emoji pair. We could write it all out for each emoji pair, but since the code is identical (except for the contexts and the emojis), it is much more efficient to define a **function** to do this.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_concern_surprise\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n![](images/CS_RoseGina_plot_concern_surprise.png)\n\n::: {.callout-note title=\"Defining our own functions\"}\nFunctions are reusable code snippets that perform specific tasks. So far, we have only used built-in `R` functions (see @sec-RFunctions) and functions from add-on packages such {dplyr} from the tidyverse (see @sec-tidyverse), but we have not defined our own functions.\n\nDefining our own functions can help us make our code more efficient and organised. As a rule of thumb, whenever writing new code seems redundant (i.e., when you find yourself copying and pasting entire sections of code), it is best to define a function for that task. This is will ensure that the task is always performed in the same way and, if you find that you need to amend the code to perform the task, you will only need to make the change once, within the function assigned to this task.\n\nThe basic structure of a function is `function(argument)`. Looks familiar? Accordingly, we define a function the following way: `function(parameters){function body}`\n\nHere are the steps:\n\n1.  We define a function using the keyword `function`. After this keyword, we write a list of **parameters** in brackets. **Parameters** act as placeholders for the function's arguments.\n2.  We then write code in the **function body** and enclose it in curly brackets. The **function body** tells the function what it is meant to do when called upon.\n3.  We assign our function a name using the assignment operator (`<-)`. This name will be used to call up the function. To avoid conflicts (see @sec-Conflicts), we choose a name that is not already assigned to a built-in function.\n:::\n\nIn our case, the process of defining a plotting function is straightforward:\n\n1.  We start with the keyword `function()` and state that our function should take `contexts` as its first argument and `emojis` as its second argument, as only these change with each plot.\n2.  We then simply paste the code that we just wrote for the above barplot inside the curly braces, replacing the specific contexts and emojis with the parameters of our function.\n3.  We name our function `plot_AU_matches` to make clear what it does: it plots AU matches.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_AU_matches <- function(contexts, emojis) {\n  data_AU |> \n    filter(context %in% contexts) |> \n    ggplot(aes(x = context, y = percent, fill = match)) +\n    geom_col() +\n    scale_x_discrete(limits = contexts) +\n    scale_y_continuous(expand = c(0,0)) +\n    scale_fill_manual(values = c(\"#66C2A5\", \"#E78AC3\")) +\n    geom_text(aes(label = percent), position = position_stack(vjust = 0.5)) +\n    labs (x=\"\", y = \"percent\", title = emojis) +\n    theme_classic() +\n    theme(plot.title = element_text(hjust = 0.5, size = 20), \n          legend.title=element_blank())\n}\n```\n:::\n\n\n\n\nWe the apply this function to all contexts and emoji pairs by filling them in as the arguments.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_concern_surprise <- plot_AU_matches(c(\"concern\", \"surprise\"), \"😯 😲\")\nplot_happiness_cheeky <- plot_AU_matches(c(\"happiness\", \"(cheeky) laughter\"), \"😃 😆\")\nplot_mild_irr_annoyance <- plot_AU_matches(c(\"mild irritation\", \"annoyance\"), \"😐 😑\")\nplot_mild_disapp_mod_dissap <- plot_AU_matches(c(\"mild disappointment\", \"moderate disappointment\"), \"🙁️ ☹️\")\nplot_amusement_int_happiness <- plot_AU_matches(c(\"amusement\", \"(intense) happiness\"), \"😄 😁\")\nplot_happiness2_bashfulness <- plot_AU_matches(c(\"happiness2\", \"bashfulness\"), \"😊 ☺️\")\n```\n:::\n\n\n\n\n:::: {.callout-note collapse=\"true\"}\n#### How to insert emojis in `R` and render plots with emojis 😰\n\nThere are various ways to insert emojis in R. The easiest is to use the emoji keyboard (see @fig-emoji-keyboard). To open it on MacOS, use the keyboard shortcut `Crtl + ⌘ Cmd + Space` or `🌐 fn + e` and on Windows `⊞ Win + . (period)`. The emoji keyboard is also available in RStudio, if you go to the \"Edit\" drop-down menu and click on \"Emojis & Symbols\". Alternatively, there are emoji libraries for `R`, for example {emo(ji)} [@wickham2024emoji].\n\nAs we want to display emojis within plots, we need to pay even more attention to graphics. Emojis as part of plots created by `ggplot` cannot be displayed by default. Additional problems can occur when rendering a Quarto or RMarkdown document to HTML.\n\nIf displaying emojis as part of plots in RStudio does not work for you, you will need to use the high-quality graphics library \"AGG\" (\"Anti-Grain Geometry\") or \"Cairo\" as your graphics backend in RStudio. To do this, head to the \"Tools\" drop-down menu and click on \"Global Options\". Then, go to the \"Graphics\" tab and select the \"AGG\" or \"Cairo\" option (see @fig-agg).\n\n::: {#fig-emoji-tools layout-ncol=\"2\"}\n![The emoji keyboard](images/CS_RoseGina_emoji_keyboard.png){#fig-emoji-keyboard fig-align=\"center\" width=\"270\"}\n\n![Recommended graphics backend in RStudio](images/CS_RoseGina_AGG.png){#fig-agg fig-align=\"center\" width=\"300\"}\n\nTools for inserting and displaying emojis in RStudio\n:::\n\nIf you are using AGG as your graphics backend, you can use the [{ragg}](https://ragg.r-lib.org) package [@pedersen2024ragg] to correctly render your Quarto/RMarkdown document to HTML with all the emojis in the plots. This package provides graphic devices based on AGG and includes advanced text rendering, with support for emojis. To use {ragg} in combinination with the {knitr} engine, first install the package and then add the following setup command at the beginning of your document:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"ragg\")\n\nknitr::opts_chunk$set(dev = \"ragg_png\")\n```\n:::\n\n\n\n\nIf AGG does not work for you, you can use Cairo. Cairo comes preinstalled with `R` so you don't need to install it yourself. The set-up command for your Quarto/RMarkdown document is:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(dev.args = list(png = list(type = \"cairo\")))\n```\n:::\n\n\n\n::::\n\n### Assembling plots with {patchwork} {#sec-au-patchwork}\n\nBy applying our newly created function `plot_AU_matches()` to all emoji pairs and contexts, we have created one barplot for each emoji pair. We will now use the [{patchwork}](https://patchwork.data-imaginist.com) package [@pedersen2024patchwork] to assemble the plots into one figure. As the name suggests, {patchwork} enables us to patch several plots together and arrange them as we wish. The basic operator to combine plots in {patchwork} is the `+` operator. Additionally, plots can be combined:\n\n-   Horizontally using `|` and\n-   Vertically using `/`.\n\nBrackets can be used to combine horizontal and vertical arrangements.\n\n![Patchwork artwork by [Allison Horst](https://allisonhorst.com/r-packages-functions) (CC-BY)](images/AHorst_patchwork.png){#fig-patchwork width=\"600\"}\n\nIn line with the research question of @fricke2024semantic, we want to compare the matching rates of emojis and contexts in the AU+ condition with the matching rates in the AU- condition. Our goal is therefore to create a plot that looks similar to @fig-AUFricke created by @fricke2024semantic.\n\n![Plot of individual emoji pairs that compares AU conditions [@fricke2024semantic: 11, CC-BY]](images/CS_RoseGina_Fricke_AUplot.png){#fig-AUFricke width=\"700\"}\n\nFirst, let us plan the layout of our combined plot with some placeholder names. Our combined plot will have two columns and three rows: In both `column1` and `column2`, three plots are stacked **vertically** on top of each other. These are the plots of the AU+ and the AU- condition, respectively. We then place these patchworks next to each other (**horizontally**) for comparison.\n\n```         \ncolumn1 <- p1 / p2 / p3\n\ncolumn2 <- p4 / p5 / p6\n\ncolumns_combined <- column1 | column2\n```\n\nWe follow the logic above to create our combined plot, choosing informative names for our subplots. To run this code, you will need to have the {patchwork} package installed and the library loaded.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"patchwork\")\n#library(patchwork)\n\n#AU+ condition:\nAU_plus_patch <-\n  plot_concern_surprise / plot_happiness_cheeky / plot_mild_irr_annoyance\n\n#AU- condition:\nAU_minus_patch <-\n  plot_mild_disapp_mod_dissap / plot_amusement_int_happiness / plot_happiness2_bashfulness\n```\n:::\n\n\n\n\nTo further specify the layout, we use the `plot_layout()` function from {patchwork}. By setting the \"guide\" argument to \"collect\", legends that are identical within each patchwork are merged into one. We place the legends at the bottom of each subplot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#AU+ condition:\nAU_plus_patch <- AU_plus_patch +\n  plot_layout(guides = \"collect\") & theme(legend.position = \"bottom\")\n\n#AU- condition:\nAU_minus_patch <- AU_minus_patch +\n  plot_layout(guides = \"collect\") & theme(legend.position = \"bottom\")\n```\n:::\n\n\n\n\nSince `AU_plus_patch` and `AU_minus_patch` are to be combined in one plot, we need to add titles to keep them apart. Technically, it is possible (and recommended!) to use the `plot_annotation()` function of the {patchwork} package for this. However, annotations made with this function are only shown at the highest nesting level. As we will be building a double-nested plot, any annotations we do on the \"blocks-of-three\"-level will not be displayed. We can work around this by using the function `wrap_elements()`. This fixates the blocks in their current position and allows us to add titles using `ggtitles()` instead.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAU_plus_patch <- wrap_elements(plot = AU_plus_patch) +\n  ggtitle(\"[AU+] condition\")\n\nAU_minus_patch <- wrap_elements(plot = AU_minus_patch) +\n  ggtitle(\"[AU-] condition\")\n```\n:::\n\n\n\n\nFinally, we put both columns together to get our final plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAU_plus_patch | AU_minus_patch\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n![Plot combining all six plots into one figure](images/CS_RoseGina_AUpatch_complete.png){#fig-AUpatch width=\"100%\"}\n\n@fig-AUpatch contains information on the matching rates of all emoji pairs with their contexts. It contains the same information as @fig-AUFricke from @fricke2024semantic, but does not look exactly the same. Which look do you think is easiest to interpret?\n\n:::: {.callout-note title=\"Alternative ways of dealing with the legend\" collapse=\"true\"}\nYou probably will have noticed that @fig-AUpatch contains two identical legends. This is the trade-off we take by using the `wrap_elements()` function: We have fixated the patchworks in their state with their legends, which means that the legends cannot be merged later. There are a couple of other options that will produce different outcomes, however, none is going to be perfect: Since we do not want to delete the legend completely, one option would be to keep the legends of all six plots, as in @fig-alllegends. Another option would be to keep the legend of one block and delete the other. However, as you can see in @fig-onelegend, this makes the bars take up the space of the legend, and the bars in one block become wider than in the other one.\n\n::: {#fig-AU-plot-options layout-ncol=\"2\"}\n![The combined plot with six legends](images/CS_RoseGina_AU_plot_six_legends.png){#fig-alllegends fig-align=\"center\" width=\"550\"}\n\n![The combined plot with one legend](images/CS_RoseGina_AU_plot_one_legend.png){#fig-onelegend fig-align=\"center\" width=\"550\"}\n\nOptions for the legend placement\n:::\n::::\n\n### Interpreting the plot\n\nBy looking and interpreting @fig-AUpatch, we can now finally answer the research question: Do AU differences lead to differences in meaning between the two emojis of a pair?\n\nBased on the descriptive statistics visualised in @fig-AUpatch, the answer is no, seemingly not. The AU difference does not seem to be critical when deciding which emoji to use in a specific context. The original study also concluded that the matching emoji was \"generally preferred with matching rates above chance level\" [@fricke2024semantic: 11], both in the AU+ and in the AU- condition. Now, was all this work for nothing?\n\nNo, not at all! We can still draw some interesting inferences from the plot we created. For example, we see that minor visual differences between emojis do appear to affect the understanding and selection of emojis in different contexts: By slightly varying the contexts, participants were made to choose emojis with different facial features. Notably, matching rates were quite similar within emoji pairs. In particular, this was the case for the contexts *happiness* 😃 - *(cheeky) laughter* 😆 and *happiness2* 😊 - *bashfulness* ☺️ : there was less than a 2% difference between the matching rates. Hence, there is much more to explore in future linguistics studies on the semantics of emoji in text messages!\n\nThe following quiz questions are about the interpretation of @fig-AUpatch. The questions should help you make sense of the information displayed.\n\n::: callout-tip\n#### Quiz time! {.unnumbered}\n\n[**Q6.**]{style=\"color:green;\"} In which context pair did participants choose the matching emojis most often?\n\n\n\n\n\n```{=html}\n<form name=\"form_70456\" onsubmit=\"return validate_form_70456()\" method=\"post\">\n<input type=\"radio\" name=\"answer_70456\" id=\"answer_70456_1\" value=\"mild disappointment and moderate disappointment\"/>\n<label>mild disappointment and moderate disappointment</label>\n<br/>\n<input type=\"radio\" name=\"answer_70456\" id=\"answer_70456_2\" value=\"happiness2 and bashfulness \"/>\n<label>happiness2 and bashfulness </label>\n<br/>\n<input type=\"radio\" name=\"answer_70456\" id=\"answer_70456_3\" value=\"concern and surprise\"/>\n<label>concern and surprise</label>\n<br/>\n<input type=\"radio\" name=\"answer_70456\" id=\"answer_70456_4\" value=\"mild irritation and annoyance\"/>\n<label>mild irritation and annoyance</label>\n<br/>\n<input type=\"radio\" name=\"answer_70456\" id=\"answer_70456_5\" value=\"happiness and (cheeky) laughter\"/>\n<label>happiness and (cheeky) laughter</label>\n<br/>\n<input type=\"radio\" name=\"answer_70456\" id=\"answer_70456_6\" value=\"amusement and (intense) happiness\"/>\n<label>amusement and (intense) happiness</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_70456\"></div>\n</form>\n<script>function validate_form_70456() {var x, text; var x = document.forms['form_70456']['answer_70456'].value;if (x == 'happiness and (cheeky) laughter'){text = 'That’s right! The vast majority of participants (86.79% and 88.68%) opted for the matching emoji in the contexts <em>happiness</em> (😃) and <em>(cheeky) laughter</em> (😆).';} else {text = 'Not quite, try again.';} document.getElementById('result_70456').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1;res1 = document.getElementById('result_70456').innerText == 'That’s right! The vast majority of participants (86.79% and 88.68%) opted for the matching emoji in the contexts happiness (😃) and (cheeky) laughter (😆).';text = res1;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n\n\n\n<br><br> [**Q7.**]{style=\"color:green;\"} How can a small difference (such as \\< 2%) between matching rates within pairs be interpreted?\n\n\n\n\n\n```{=html}\n<form name=\"form_59914\" onsubmit=\"return validate_form_59914()\" method=\"post\">\n<input type=\"radio\" name=\"answer_59914\" id=\"answer_59914_1\" value=\"Within these pairs, a very similar number of participants chose the matching emoji.\"/>\n<label>Within these pairs, a very similar number of participants chose the matching emoji.</label>\n<br/>\n<input type=\"radio\" name=\"answer_59914\" id=\"answer_59914_2\" value=\"Within these pairs, half the participants preferred one emoji and half preferred the other.\"/>\n<label>Within these pairs, half the participants preferred one emoji and half preferred the other.</label>\n<br/>\n<input type=\"radio\" name=\"answer_59914\" id=\"answer_59914_3\" value=\"Within these pairs, participants had the most difficulty choosing one emoji over the other.\"/>\n<label>Within these pairs, participants had the most difficulty choosing one emoji over the other.</label>\n<br/>\n<input type=\"radio\" name=\"answer_59914\" id=\"answer_59914_4\" value=\"Within these pairs, the least number of participants chose the matching emoji.\"/>\n<label>Within these pairs, the least number of participants chose the matching emoji.</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_59914\"></div>\n</form>\n<script>function validate_form_59914() {var x, text; var x = document.forms['form_59914']['answer_59914'].value;if (x == 'Within these pairs, a very similar number of participants chose the matching emoji.'){text = 'That’s right! Of course, this does not mean that the same participants preferred the matching emojis for both emojis of a pair.';} else {text = 'This is not correct. Look at the subplot <em>happiness</em> 😃 - <em>(cheeky) laughter</em> 😆 and think about its meaning.';} document.getElementById('result_59914').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2;res1 = document.getElementById('result_70456').innerText == 'That’s right! The vast majority of participants (86.79% and 88.68%) opted for the matching emoji in the contexts happiness (😃) and (cheeky) laughter (😆).'; res2 = document.getElementById('result_59914').innerText == 'That’s right! Of course, this does not mean that the same participants preferred the matching emojis for both emojis of a pair.';text = res1 + res2;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n```{=html}\n<div id=\"hint_42843\" onclick=\"return show_hint_42843()\">🐭 Click on the mouse for a hint.</div>\n<div id=\"result_42843\" onclick=\"return show_hint_42843()\"></div>\n<script>function show_hint_42843(){var x = document.getElementById('result_42843').innerHTML; if(!x){document.getElementById('result_42843').innerHTML = 'A small difference implies that the <em>match</em> / <em>no match</em> ratio is very similar across contexts. For example, this is the case in the subplot <em>happiness</em> 😃 - <em>(cheeky) laughter</em> 😆.';} else {document.getElementById('result_42843').innerHTML = '';}}</script>\n```\n\n\n\n\n<br> [**Q8.**]{style=\"color:green;\"} Looking at the final patchwork (@fig-AUpatch), which subplot stands out the most?\n\n\n\n\n\n```{=html}\n<form name=\"form_75728\" onsubmit=\"return validate_form_75728()\" method=\"post\">\n<input type=\"radio\" name=\"answer_75728\" id=\"answer_75728_1\" value=\"lower right\"/>\n<label>lower right</label>\n<br/>\n<input type=\"radio\" name=\"answer_75728\" id=\"answer_75728_2\" value=\"lower left\"/>\n<label>lower left</label>\n<br/>\n<input type=\"radio\" name=\"answer_75728\" id=\"answer_75728_3\" value=\"upper left\"/>\n<label>upper left</label>\n<br/>\n<input type=\"radio\" name=\"answer_75728\" id=\"answer_75728_4\" value=\"middle right\"/>\n<label>middle right</label>\n<br/>\n<input type=\"radio\" name=\"answer_75728\" id=\"answer_75728_5\" value=\"middle left\"/>\n<label>middle left</label>\n<br/>\n<input type=\"radio\" name=\"answer_75728\" id=\"answer_75728_6\" value=\"upper right\"/>\n<label>upper right</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_75728\"></div>\n</form>\n<script>function validate_form_75728() {var x, text; var x = document.forms['form_75728']['answer_75728'].value;if (x == 'lower left'){text = 'Correct! The emoji pair <em>mild irritation</em> 😐 - <em>annoyance</em> 😑 sets itself apart from the rest: There is a considerable difference between the matching rates. Perhaps counterintuitively, this means that most participants opted for the same emoji in both contexts.';} else {text = 'Not quite. Which plot looks significantly different than the others?';} document.getElementById('result_75728').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3;res1 = document.getElementById('result_70456').innerText == 'That’s right! The vast majority of participants (86.79% and 88.68%) opted for the matching emoji in the contexts happiness (😃) and (cheeky) laughter (😆).'; res2 = document.getElementById('result_59914').innerText == 'That’s right! Of course, this does not mean that the same participants preferred the matching emojis for both emojis of a pair.'; res3 = document.getElementById('result_75728').innerText == 'Correct! The emoji pair mild irritation 😐 - annoyance 😑 sets itself apart from the rest: There is a considerable difference between the matching rates. Perhaps counterintuitively, this means that most participants opted for the same emoji in both contexts.';text = res1 + res2 + res3;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n\n\n\n<br><br> [**Q9.**]{style=\"color:green;\"} Which interpretations of the lower left plot are correct? Select all that apply.\n\n\n\n\n\n```{=html}\n<form name=\"form_32613\" onsubmit=\"return validate_form_32613()\" method=\"post\">\n<input type=\"checkbox\" id=\"answer_32613_1\" value=\"The disparate matching rates of the 😐😑 pair prove that, in general, AU differences affect participants&#39; preferences.\"/>\n<label>The disparate matching rates of the 😐😑 pair prove that, in general, AU differences affect participants' preferences.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_32613_2\" value=\"There is a major difference between the matching rates of the annoyance and happiness contexts.\"/>\n<label>There is a major difference between the matching rates of the annoyance and happiness contexts.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_32613_3\" value=\"The emoji 😐 was selected for its matching context considerably less often than all the other emojis.\"/>\n<label>The emoji 😐 was selected for its matching context considerably less often than all the other emojis.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_32613_4\" value=\"Only in the 😐😑 pair does the matching rate for one emoji exceed chance level, while the matching rate for the other falls below chance.\"/>\n<label>Only in the 😐😑 pair does the matching rate for one emoji exceed chance level, while the matching rate for the other falls below chance.</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_32613\"></div>\n</form>\n<script>function validate_form_32613() {var text; var x1 = document.getElementById('answer_32613_1'); var x2 = document.getElementById('answer_32613_2'); var x3 = document.getElementById('answer_32613_3'); var x4 = document.getElementById('answer_32613_4'); if (x1.checked == false&x2.checked == false&x3.checked == true&x4.checked == true){text = 'That’s right! Apparently, two thirds (66.67 %) of participants favoured the non matching emoji in the <em>mild irritation</em>-context: Instead of 😐, they chose 😑. One of the narratives in this context was ‘a malfunctioning wifi router’. Which emoji would you choose in this context, 😐 or 😑?';} else {text = 'Not quite. Consider the implications of a low matching rate versus a high matching rate.';} document.getElementById('result_32613').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4;res1 = document.getElementById('result_70456').innerText == 'That’s right! The vast majority of participants (86.79% and 88.68%) opted for the matching emoji in the contexts happiness (😃) and (cheeky) laughter (😆).'; res2 = document.getElementById('result_59914').innerText == 'That’s right! Of course, this does not mean that the same participants preferred the matching emojis for both emojis of a pair.'; res3 = document.getElementById('result_75728').innerText == 'Correct! The emoji pair mild irritation 😐 - annoyance 😑 sets itself apart from the rest: There is a considerable difference between the matching rates. Perhaps counterintuitively, this means that most participants opted for the same emoji in both contexts.'; res4 = document.getElementById('result_32613').innerText == 'That’s right! Apparently, two thirds (66.67 %) of participants favoured the non matching emoji in the mild irritation-context: Instead of 😐, they chose 😑. One of the narratives in this context was ‘a malfunctioning wifi router’. Which emoji would you choose in this context, 😐 or 😑?';text = res1 + res2 + res3 + res4;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n```{=html}\n<div id=\"hint_76701\" onclick=\"return show_hint_76701()\">🐭 Click on the mouse for a hint.</div>\n<div id=\"result_76701\" onclick=\"return show_hint_76701()\"></div>\n<script>function show_hint_76701(){var x = document.getElementById('result_76701').innerHTML; if(!x){document.getElementById('result_76701').innerHTML = 'Two statements are correct. A low matching rate indicates that participants rarely chose the emoji that was intended for the context, that is, the emoji that the authors identified as the most fitting.';} else {document.getElementById('result_76701').innerHTML = '';}}</script>\n```\n\n\n\n\n<br><br> [**Q10.**]{style=\"color:green;\"} What are plausible reasons for the striking results presented in the lower left barplot? Select all that apply.\n\n\n\n\n\n```{=html}\n<form name=\"form_34218\" onsubmit=\"return validate_form_34218()\" method=\"post\">\n<input type=\"checkbox\" id=\"answer_34218_1\" value=\"The participants did not realize there was a difference between 😐 and 😑.\"/>\n<label>The participants did not realize there was a difference between 😐 and 😑.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_34218_2\" value=\"The stories created for mild irritation and annoyance triggered a similar reaction.\"/>\n<label>The stories created for mild irritation and annoyance triggered a similar reaction.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_34218_3\" value=\"The stories of the mild irritation context were perceived as more annoying than the authors had anticipated.\"/>\n<label>The stories of the mild irritation context were perceived as more annoying than the authors had anticipated.</label>\n<br/>\n<input type=\"checkbox\" id=\"answer_34218_4\" value=\"Unlike what was anticipated, most participants used the emojis 😐 and 😑 in very different contexts.\"/>\n<label>Unlike what was anticipated, most participants used the emojis 😐 and 😑 in very different contexts.</label>\n<br/>\n<input type=\"submit\" value=\"Check answer\"/>\n<div id=\"result_34218\"></div>\n</form>\n<script>function validate_form_34218() {var text; var x1 = document.getElementById('answer_34218_1'); var x2 = document.getElementById('answer_34218_2'); var x3 = document.getElementById('answer_34218_3'); var x4 = document.getElementById('answer_34218_4'); if (x1.checked == false&x2.checked == true&x3.checked == true&x4.checked == false){text = 'That’s right! These are two possible explanations. However, as we have no way of tracking the participants’ reasoning, we can only make some educated guesses.';} else {text = 'Not quite. Consider what could have caused the differing matching rates.';} document.getElementById('result_34218').innerHTML = text; evaluate_final_score(); return false;}function evaluate_final_score(){\n         element = document.getElementById('checkdown_final_score');\n         if(element === null){return false;} else {var element, text, res1, res2, res3, res4, res5;res1 = document.getElementById('result_70456').innerText == 'That’s right! The vast majority of participants (86.79% and 88.68%) opted for the matching emoji in the contexts happiness (😃) and (cheeky) laughter (😆).'; res2 = document.getElementById('result_59914').innerText == 'That’s right! Of course, this does not mean that the same participants preferred the matching emojis for both emojis of a pair.'; res3 = document.getElementById('result_75728').innerText == 'Correct! The emoji pair mild irritation 😐 - annoyance 😑 sets itself apart from the rest: There is a considerable difference between the matching rates. Perhaps counterintuitively, this means that most participants opted for the same emoji in both contexts.'; res4 = document.getElementById('result_32613').innerText == 'That’s right! Apparently, two thirds (66.67 %) of participants favoured the non matching emoji in the mild irritation-context: Instead of 😐, they chose 😑. One of the narratives in this context was ‘a malfunctioning wifi router’. Which emoji would you choose in this context, 😐 or 😑?'; res5 = document.getElementById('result_34218').innerText == 'That’s right! These are two possible explanations. However, as we have no way of tracking the participants’ reasoning, we can only make some educated guesses.';text = res1 + res2 + res3 + res4 + res5;element.innerHTML = text;\n         return false;\n         }}</script>\n```\n\n```{=html}\n<div id=\"hint_42693\" onclick=\"return show_hint_42693()\">🐭 Click on the mouse for a hint.</div>\n<div id=\"result_42693\" onclick=\"return show_hint_42693()\"></div>\n<script>function show_hint_42693(){var x = document.getElementById('result_42693').innerHTML; if(!x){document.getElementById('result_42693').innerHTML = 'Two of these are plausible reasons for the observed result. The plot suggests that participants preferred the same emoji for the stories associated with <em>mild irritation</em> and <em>annoyance</em>.';} else {document.getElementById('result_42693').innerHTML = '';}}</script>\n```\n\n\n\n\n<br>\n:::\n\nOverall, @fig-AUpatch shows that there was indeed a preference for context-matching emojis. However, the findings do not support the pictorial approach adopted by @fricke2024semantic: Whether or not emoji features coincided with human facial features, did not (significantly) affect the participants' decision for one emoji or the other.\n\n## Conclusion {#sec-conclusion}\n\nYou have successfully completed [`<span id=\"checkdown_final_score\">0</span>`{=html} out of 10 quiz questions]{style=\"color:green;\"} in this chapter.\n\nYou are now a pro in handling (stacked) barplots! You can build, customise, arrange, and interpret them. Barplots are powerful for visualising categorical data, offering a straightforward way to compare frequencies and make patterns apparent. However, they do have their limitations. For instance, they are not ideal for displaying continuous data. Building and assembling plots can be quite fiddly and it can take some trial-and-error to make the plot look like what you had imagined. But there is a solution for (almost) everything and hopefully, the beautiful plot you create in the process will be worth the effort.\n\nThis chapter's analysis revealed gender-specific differences in emoji understanding, potentially indicating a gender confidence gap between men and women. On average, however, both genders, reported at least a good understanding of emojis. The visualisations have been adjusted for the gender imbalance in the data, demonstrating the importance of accounting for differences in group sizes.\n\nIn this chapter, we have created an informative figure that answers the experiment’s research question by combining multiple plots. The question whether Action Unit (AU) differences are critical for emoji preference was answered in the negative. However, we have made several other discoveries along the way: As noted by @fricke2024semantic, we have found that small changes of emojis’ facial features do affect choice patterns.\n\nEmojis, it turns out, contain lots of information, and there is a science behind them 🤓. While experimentally measuring why we prefer certain emojis over other ones represents a real challenge, @fricke2024semantic provides valuable insights into this fascinating area of study. As the authors shared their data and code, we were able to successfully reproduce their results, as well as create new informative figures on the basis of their data.\n\n## References {.unnumbered}\n\nFricke, Lea, Patrick G Grosz, and Tatjana Scheffler. 2024. Semantic Differences in Visually Similar Face Emojis. *Language and Cognition*. Cambridge University Press 1–15. <https://doi.org/10.1017/langcog.2024.12>.\n\nFugate, Jennifer MB & Courtny L Franco. 2021. Implications for Emotion: Using Anatomically Based Facial Coding to Compare Emoji Faces Across Platforms. *Frontiers in Psychology*. Frontiers Media SA 12. 605928. <https://doi.org/10.3389/fpsyg.2021.605928>.\n\nMaier, Emar. 2023. Emojis as Pictures. *Ergo* 10. <https://doi.org/10.3998/ergo.4641>.\n\nNeuwirth, Erich. 2022. Package \"RColorBrewer\". *ColorBrewer Palettes* 991. <https://cran.r-project.org/web/packages/RColorBrewer/RColorBrewer.pdf>.\n\nPedersen, Thomas Lin. 2024. *Patchwork: The Composer of Plots*. <https://patchwork.data-imaginist.com>.\n\nPedersen, Thomas Lin & Maxim Shemanarev. 2024. *Ragg: Graphic Devices Based on AGG*. <https://ragg.r-lib.org>.\n\nPfeifer, Valeria A, Emma L Armstrong & Vicky Tzuyin Lai. 2022. Do all facial emojis communicate emotion? The impact of facial emojis on perceived sender emotion and text processing. *Computers in Human Behavior*. Elsevier 126. 107016. <https://doi.org/10.1016/j.chb.2021.107016>.\n\nScheffler, Tatjana & Ivan Nenchev. 2024. Affective, semantic, frequency, and descriptive norms for 107 face emojis. *Behavior Research Methods*. Springer 1–22. <https://doi.org/10.3758/s13428-024-02444-x>.\n\nWickham, Hadley, Romain François & Lucy D’Agostino McGowan. 2024. *Emo: Easily Insert ’emoji’*. <https://github.com/hadley/emo>.\n\n### Packages used in this chapter {.unnumbered}\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.4.1 (2024-06-14)\nPlatform: aarch64-apple-darwin20\nRunning under: macOS 15.1\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\ntime zone: Europe/Brussels\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] knitcitations_1.0.12 ragg_1.3.3           patchwork_1.2.0     \n [4] lubridate_1.9.3      forcats_1.0.0        stringr_1.5.1       \n [7] dplyr_1.1.4          purrr_1.0.2          readr_2.1.5         \n[10] tidyr_1.3.1          tibble_3.2.1         ggplot2_3.5.1       \n[13] tidyverse_2.0.0      here_1.0.1           checkdown_0.0.12    \n[16] webexercises_1.1.0  \n\nloaded via a namespace (and not attached):\n [1] utf8_1.2.4        generics_0.1.3    xml2_1.3.6        stringi_1.8.4    \n [5] hms_1.1.3         digest_0.6.36     magrittr_2.0.3    evaluate_0.24.0  \n [9] grid_4.4.1        timechange_0.3.0  fastmap_1.2.0     plyr_1.8.9       \n[13] rprojroot_2.0.4   jsonlite_1.8.8    backports_1.5.0   httr_1.4.7       \n[17] fansi_1.0.6       scales_1.3.0      codetools_0.2-20  bibtex_0.5.1     \n[21] textshaping_0.4.0 cli_3.6.3         rlang_1.1.4       commonmark_1.9.1 \n[25] munsell_0.5.1     withr_3.0.1       yaml_2.3.8        tools_4.4.1      \n[29] tzdb_0.4.0        colorspace_2.1-0  vctrs_0.6.5       R6_2.5.1         \n[33] lifecycle_1.0.4   RefManageR_1.4.0  htmlwidgets_1.6.4 pkgconfig_2.0.3  \n[37] pillar_1.9.0      gtable_0.3.5      Rcpp_1.0.12       glue_1.7.0       \n[41] systemfonts_1.1.0 xfun_0.45         tidyselect_1.2.1  rstudioapi_0.16.0\n[45] knitr_1.47        farver_2.1.2      htmltools_0.5.8.1 labeling_0.4.3   \n[49] rmarkdown_2.27    compiler_4.4.1    markdown_1.13    \n```\n\n\n:::\n:::\n\n\n\n\n### Package references {.unnumbered}\n\n\n\n\n[1] D. Barr and L. DeBruine. _webexercises: Create Interactive Web\nExercises in R Markdown (Formerly webex)_. R package version 1.1.0.\n2023. <https://github.com/psyteachr/webexercises>.\n\n[2] C. Boettiger. _knitcitations: Citations for Knitr Markdown Files_.\nR package version 1.0.12. 2021.\n<https://github.com/cboettig/knitcitations>.\n\n[3] G. Grolemund and H. Wickham. \"Dates and Times Made Easy with\nlubridate\". In: _Journal of Statistical Software_ 40.3 (2011), pp.\n1-25. <https://www.jstatsoft.org/v40/i03/>.\n\n[4] G. Moroz. _checkdown: Check-Fields and Check-Boxes for rmarkdown_.\nR package version 0.0.12. 2023.\n<https://agricolamz.github.io/checkdown/>.\n\n[5] G. Moroz. _Create check-fields and check-boxes with checkdown_.\n2020. <https://CRAN.R-project.org/package=checkdown>.\n\n[6] K. Müller. _here: A Simpler Way to Find Your Files_. R package\nversion 1.0.1. 2020. <https://here.r-lib.org/>.\n\n[7] K. Müller and H. Wickham. _tibble: Simple Data Frames_. R package\nversion 3.2.1. 2023. <https://tibble.tidyverse.org/>.\n\n[8] T. L. Pedersen. _patchwork: The Composer of Plots_. R package\nversion 1.2.0. 2024. <https://patchwork.data-imaginist.com>.\n\n[9] T. L. Pedersen and M. Shemanarev. _ragg: Graphic Devices Based on\nAGG_. R package version 1.3.3. 2024. <https://ragg.r-lib.org>.\n\n[10] R Core Team. _R: A Language and Environment for Statistical\nComputing_. R Foundation for Statistical Computing. Vienna, Austria,\n2024. <https://www.R-project.org/>.\n\n[11] V. Spinu, G. Grolemund, and H. Wickham. _lubridate: Make Dealing\nwith Dates a Little Easier_. R package version 1.9.3. 2023.\n<https://lubridate.tidyverse.org>.\n\n[12] H. Wickham. _forcats: Tools for Working with Categorical Variables\n(Factors)_. R package version 1.0.0. 2023.\n<https://forcats.tidyverse.org/>.\n\n[13] H. Wickham. _ggplot2: Elegant Graphics for Data Analysis_.\nSpringer-Verlag New York, 2016. ISBN: 978-3-319-24277-4.\n<https://ggplot2.tidyverse.org>.\n\n[14] H. Wickham. _stringr: Simple, Consistent Wrappers for Common\nString Operations_. R package version 1.5.1. 2023.\n<https://stringr.tidyverse.org>.\n\n[15] H. Wickham. _tidyverse: Easily Install and Load the Tidyverse_. R\npackage version 2.0.0. 2023. <https://tidyverse.tidyverse.org>.\n\n[16] H. Wickham, M. Averick, J. Bryan, et al. \"Welcome to the\ntidyverse\". In: _Journal of Open Source Software_ 4.43 (2019), p. 1686.\nDOI: 10.21105/joss.01686.\n\n[17] H. Wickham, W. Chang, L. Henry, et al. _ggplot2: Create Elegant\nData Visualisations Using the Grammar of Graphics_. R package version\n3.5.1. 2024. <https://ggplot2.tidyverse.org>.\n\n[18] H. Wickham, R. François, L. Henry, et al. _dplyr: A Grammar of\nData Manipulation_. R package version 1.1.4. 2023.\n<https://dplyr.tidyverse.org>.\n\n[19] H. Wickham and L. Henry. _purrr: Functional Programming Tools_. R\npackage version 1.0.2. 2023. <https://purrr.tidyverse.org/>.\n\n[20] H. Wickham, J. Hester, and J. Bryan. _readr: Read Rectangular Text\nData_. R package version 2.1.5. 2024. <https://readr.tidyverse.org>.\n\n[21] H. Wickham, D. Vaughan, and M. Girlich. _tidyr: Tidy Messy Data_.\nR package version 1.3.1. 2024. <https://tidyr.tidyverse.org>.\n\n[22] Y. Xie. _Dynamic Documents with R and knitr_. 2nd. ISBN\n978-1498716963. Boca Raton, Florida: Chapman and Hall/CRC, 2015.\n<https://yihui.org/knitr/>.\n\n[23] Y. Xie. \"knitr: A Comprehensive Tool for Reproducible Research in\nR\". In: _Implementing Reproducible Computational Research_. Ed. by V.\nStodden, F. Leisch and R. D. Peng. ISBN 978-1466561595. Chapman and\nHall/CRC, 2014.\n\n[24] Y. Xie. _knitr: A General-Purpose Package for Dynamic Report\nGeneration in R_. R package version 1.47. 2024.\n<https://yihui.org/knitr/>.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}