# Ch. 4: Tasks & Quizzes {.unnumbered}

::: {.callout-tip collapse="false"}
#### Your turn! {.unnumbered}

[**Q4.1**]{style="color:green;"} Which of these packages is not part of base `R`?

```{r}
#| echo: false
#| label: "Q4.1"
library(checkdown)
check_question("{ggplot2}", options = c("{datasets}", "{graphics}", "{ggplot2}", "{stats}"), type = "radio",
button_label = "Check answer", q_id = "Q4.1",
random_answer_order = TRUE,
right = "Correct! Though later on, we will install {ggplot2} as part of the {tidyverse} bundle of packages.",
wrong = "No, this package is part of the base installation.")
```

[**Q4.2**]{style="color:green;"} Is it possible to create an `R` package that provides access to the full texts of all of Jane Austen's published novels for computational text analysis in `R`?

```{r}
#| echo: false
#| label: "Q4.2"

check_question("Yes, pretty much anything is possible in R!", options = c("Yes, pretty much anything is possible in R!", "No way, that sounds impossible!"), type = "radio",
button_label = "Check answer", q_id = "Q4.2",
right = "Not only is it possible, but it has already been done. And what's more, the creator of the package has shared it for the entire R community to use. 🎉",
wrong = "Not only is it possible, but it has already been done. And what's more, the creator of the package has shared it for the entire R community to use!")

```

[**Q4.3**]{style="color:green;"} Is the {janeaustenr} package installed as part of base `R`?

```{r}
#| echo: false
#| label: "Q4.3"

check_question("No", options = c("Yes", "No"), type = "radio",
button_label = "Check answer", q_id = "Q4.3",
right = "Correct. And, in the next section, you will learn how to install it!",
wrong = "No, it's not. If you can find it in your Packages pane, this means that you installed it at some point.")

```
:::
::: {.callout-tip collapse="false"}
#### Your turn! {.unnumbered}

[**Q4.4**]{style="color:green;"} Which is the correct `R` object name to access Jane Austen's novel 'Sense and Sensibility'?

```{r}
#| echo: false
#| label: "Q4.4"

check_question("sensesensibility", options = c("sensesensibility", "Sensesensibility", "senseandsensibility", "Sense&Sensibility", "Sense and Sensibility"), type = "radio",
button_label = "Check answer", 
random_answer_order = TRUE,
q_id = "Q4.4", 
right = "That's right!",
wrong = "No, if you enter this name in the Console, it will return an \"object not found\" error.")
```

[**Q4.5**]{style="color:green;"} What is the source for the `R` object containing Jane Austen's novel 'Sense and Sensibility'?

```{r}
#| echo: false
#| label: "Q4.5"

check_question("http://www.gutenberg.org/ebooks/161", 
               options = c("http://www.gutenberg.org/ebooks/161", "https://en.wikipedia.org/wiki/Sense_and_Sensibility", "https://www.goodreads.com/book/show/14935.Sense_and_Sensibility", "https://jasna.org/austen/works/sense-sensibility/"),
               type = "radio",
button_label = "Check answer",
q_id = "Q4.5", 
random_answer_order = TRUE,
right = "That's right!",
wrong = "No, that's incorrect.")

check_hint("Check the object's help file to find out the exact source.", 
           hint_title = "🐭 Click on the mouse for a hint.")
```

[**Q4.6**]{style="color:green;"} What is the first word of the 66^th^ line in the `R` object containing Jane Austen's novel 'Sense and Sensibility'?

```{r}
#| echo: false
#| label: "Q4.6"

check_question("cheerful", 
button_label = "Check answer", 
random_answer_order = TRUE,
q_id = "Q4.6", 
right = "That's right! Isn't that a wonderful word?",
wrong = "No, that's not it.")

check_hint("To display a line in the Console, you need to type the name of the object immediately followed by the number of the line that you are interested in squared brackets.", 
           hint_title = "🐭 Click on the mouse for a hint.")
```
:::
### Check your progress 🌟 {.unnumbered}

You have successfully completed [`r checkdown::insert_score()` out of 6 questions]{style="color:green;"} in this chapter.
